# Generated by Django 6.0.6 on 2026-08-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_menu_code_alter_role_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledatapermission',
            name='resource_type',
            field=models.CharField(choices=[('company', 'Company'), ('branch', 'Branch'), ('location', 'Location'), ('division', 'Division'), ('department', 'Department'), ('section', 'Section'), ('cost_center', 'Cost Center'), ('warehouse', 'Warehouse'), ('project', 'Project'), ('iup', 'IUP'), ('own', 'Own Data')], max_length=50),
        ),
    ]
