# Generated by Django 6.0.6 on 2026-08-11 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='data_scope_level',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('branch', 'Branch'), ('location', 'Location'), ('division', 'Division'), ('department', 'Department'), ('section', 'Section'), ('cost_center', 'Cost Center')], default='', help_text="Wajib diisi kalau modenya 'Ikut Penempatan Pemegang'. Location untuk admin per site, Company untuk yang melayani satu perusahaan penuh.", max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='data_scope_mode',
            field=models.CharField(choices=[('all', 'Seluruh Data'), ('own', 'Ikut Penempatan Pemegang'), ('explicit', 'Pilih Sendiri')], default='explicit', help_text="Dari mana cakupan data dihitung. 'Ikut Penempatan Pemegang' membuat satu role melayani semua site — yang disimpan aturannya, bukan nama sitenya.", max_length=20),
        ),
        migrations.CreateModel(
            name='UserDataPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('company', 'Company'), ('branch', 'Branch'), ('location', 'Location'), ('division', 'Division'), ('department', 'Department'), ('section', 'Section'), ('cost_center', 'Cost Center'), ('warehouse', 'Warehouse'), ('project', 'Project'), ('iup', 'IUP'), ('own', 'Own Data')], max_length=50)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user_data_permission',
                'ordering': ['user__username', 'resource_type', 'resource_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'resource_type', 'resource_id'), name='uniq_accounts_user_data_permission')],
            },
        ),
    ]
