# Generated by Django 6.0.6 on 2026-08-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_data_scope_level_role_data_scope_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemenupermission',
            name='visibility_rule',
            field=models.CharField(choices=[('always', 'Always'), ('roster_only', 'Roster Employees Only'), ('non_roster_only', 'Non-Roster Employees Only')], default='always', help_text='Syarat tambahan di atas centang ini. Pola kerja pegawai dibaca dari Roster Crew atau Roster Policy pada penempatannya.', max_length=20),
        ),
    ]
