# Generated by Django 6.0.6 on 2026-09-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rolemenupermission_visibility_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('id', 'Bahasa Indonesia')], default='en', help_text='Bahasa antarmuka. Tidak memengaruhi zona waktu maupun data bisnis.', max_length=10),
        ),
    ]
