# Generated by Django 6.0.6 on 2026-09-11 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_roleassignment_alter_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='authority_level',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('branch', 'Branch'), ('location', 'Location'), ('division', 'Division'), ('department', 'Department'), ('section', 'Section'), ('cost_center', 'Cost Center')], default='', help_text="Tingkat organisasi untuk mode 'Ikut Penempatan Pemegang'.", max_length=20),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='authority_mode',
            field=models.CharField(blank=True, choices=[('unrestricted', 'Tanpa Batas'), ('placement', 'Ikut Penempatan Pemegang'), ('explicit', 'Ditentukan Sendiri')], default='', help_text='Dari mana kewenangan penugasan ini dihitung. Kosong berarti belum ditentukan — yang berlaku konfigurasi cakupan milik Role-nya.', max_length=20),
        ),
        migrations.CreateModel(
            name='RoleAssignmentAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('company', 'Company'), ('branch', 'Branch'), ('location', 'Location'), ('division', 'Division'), ('department', 'Department'), ('section', 'Section'), ('cost_center', 'Cost Center'), ('warehouse', 'Warehouse'), ('project', 'Project'), ('iup', 'IUP'), ('own', 'Own Data')], max_length=50)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='accounts.roleassignment')),
            ],
            options={
                'db_table': 'accounts_role_assignment_authority',
                'ordering': ['assignment', 'resource_type', 'resource_id'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'resource_type', 'resource_id'), name='uniq_role_assignment_authority')],
            },
        ),
    ]
