# Generated by Django 6.0.6 on 2026-10-01 13:27

"""
POLICY-1A — syarat menu berbasis Feature Applicability, eksplisit.

Sebelum ini menu Travel Request / Business Trip memakai `roster_only` /
`non_roster_only`, lalu POLICY-1 membaca nilai itu sebagai penanda
Employee Group **khusus di dua rute itu** — nilai yang sama berarti dua
hal tergantung rutenya. Migrasi ini menambah dua pilihan yang menyebut
artinya sendiri (`field_break`, `business_trip`) dan memindahkan tepat
dua pasangan bawaan `seed_menus.MENU_RULES` ke nilai barunya:

    /hr/travel-requests  roster_only      -> field_break
    /hr/business-trips   non_roster_only  -> business_trip

Hanya pasangan persis itu. Rute lain dan nilai lain di kedua rute itu
(`always`, atau kombinasi lain yang disetel tangan) tidak disentuh, dan
kini dibaca menurut arti harfiahnya. Baris yang dihapus lunak ikut
dipindah supaya pemulihannya tidak menghidupkan nilai lama.
"""

from django.db import migrations, models


TRAVEL_REQUEST_ROUTE = "/hr/travel-requests"
BUSINESS_TRIP_ROUTE = "/hr/business-trips"

FORWARD = (
    (TRAVEL_REQUEST_ROUTE, "roster_only", "field_break"),
    (BUSINESS_TRIP_ROUTE, "non_roster_only", "business_trip"),
)


def to_feature_rules(apps, schema_editor):
    RoleMenuPermission = apps.get_model("accounts", "RoleMenuPermission")

    for route, old, new in FORWARD:
        RoleMenuPermission.objects.filter(
            menu__route=route,
            visibility_rule=old,
        ).update(visibility_rule=new)


def to_roster_rules(apps, schema_editor):
    """
    Kebalikannya: nilai fitur dikembalikan ke nilai pola kerja yang dulu
    dipakai sebagai penggantinya, di rute mana pun — pilihan lama tidak
    mengenal nilai fitur sama sekali.
    """
    RoleMenuPermission = apps.get_model("accounts", "RoleMenuPermission")

    RoleMenuPermission.objects.filter(
        visibility_rule="field_break",
    ).update(visibility_rule="roster_only")

    RoleMenuPermission.objects.filter(
        visibility_rule="business_trip",
    ).update(visibility_rule="non_roster_only")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_consolidate_site_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemenupermission',
            name='visibility_rule',
            field=models.CharField(choices=[('always', 'Always'), ('roster_only', 'Roster Employees Only'), ('non_roster_only', 'Non-Roster Employees Only'), ('field_break', 'Field Break Applicable (Employee Group)'), ('business_trip', 'Business Trip Applicable (Employee Group)')], default='always', help_text='Syarat tambahan di atas centang ini. Roster/Non-Roster dibaca dari Roster Crew atau Roster Policy pada penempatannya; Field Break/Business Trip dari Employee Group pegawainya.', max_length=20),
        ),
        migrations.RunPython(to_feature_rules, to_roster_rules),
    ]
