# Generated by Django 6.0.6 on 2026-09-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_adopt_administration_fiscal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['fiscal_year_id', 'period_number'], 'permissions': [('post_soft_closed_period', 'Can post to soft-closed accounting period'), ('reopen_locked_period', 'Can reopen locked accounting period')]},
        ),
    ]
