# Generated by Django 6.0.6 on 2026-09-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_accounting_period_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingpolicy',
            name='auto_post',
            field=models.BooleanField(default=True, help_text='Aktif = jurnal yang lahir dari kejadian ini langsung dibukukan ke buku besar. Nonaktif = jurnalnya terbit sebagai DRAFT dan menunggu alur persetujuan Finance.'),
        ),
    ]
