# Generated by Django 6.0.6 on 2026-09-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_accounting_policy_auto_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('post_journal', 'Can post journal to the general ledger'), ('reverse_journal', 'Can reverse posted journal')]},
        ),
    ]
