# Generated by Django 6.0.6 on 2026-09-23 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_journal_action_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingevent',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='finance.accountingevent'),
        ),
        migrations.AlterField(
            model_name='accountingevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=20),
        ),
    ]
