# Generated by Django 6.0.6 on 2026-08-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='max_sites',
            new_name='max_locations',
        ),
    ]
