# Generated by Django 6.0.6 on 2026-08-13 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_rolemenupermission_visibility_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='', help_text='Nama ikon bergaya Nuxt UI, mis. `i-lucide-rocket`. Nama yang tidak dikenal jatuh ke ikon bawaan tanpa error.', max_length=64)),
                ('module', models.CharField(blank=True, default='', help_text='Modul yang dijelaskan kategori ini (`hr`, `payroll`, `administration`). Dikosongkan = panduan umum.', max_length=50)),
                ('is_published', models.BooleanField(default=True, help_text='Dimatikan: kategori beserta seluruh artikelnya hilang dari Help Center, tapi tetap bisa disunting di sini.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help Category',
                'verbose_name_plural': 'Help Categories',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Kode tetap untuk seed. Tidak tampil ke pembaca.', max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='Bagian URL artikel. Dikosongkan = diturunkan dari judul.', max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, default='', help_text='Satu kalimat yang tampil di kartu daftar. Ini yang dibaca orang sebelum memutuskan membuka artikelnya.', max_length=300)),
                ('content', models.TextField(blank=True, default='', help_text='Isi panduan.')),
                ('icon', models.CharField(blank=True, default='', help_text='Mis. `i-lucide-calendar-check`. Kosong = ikut kategori.', max_length=64)),
                ('keywords', models.CharField(blank=True, default='', help_text="Kata kunci tambahan untuk pencarian, dipisah koma. Untuk istilah yang dipakai pengguna tapi tidak ada di isi artikel — mis. 'ijin' untuk artikel berjudul 'Cuti'.", max_length=300)),
                ('route_prefix', models.CharField(blank=True, default='', help_text='Rute layar yang dijelaskan, mis. `/hr/leave`. Dipakai tombol Help di layar itu. Dikosongkan = tidak menempel ke layar mana pun.', max_length=120)),
                ('video_url', models.URLField(blank=True, default='', help_text='Tautan video tutorial, kalau ada.', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Hanya yang Published yang muncul di Help Center.', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Diisi otomatis saat status berubah jadi Published.', null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Urutan dalam kategorinya. Angka kecil di atas.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, help_text='Dikosongkan = terbaca semua pengguna. Diisi kalau panduannya memang hanya untuk pemegang role tertentu (mis. panduan admin). Ini penyaring tampilan, bukan penjagaan rahasia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_articles', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='helpcenter.helpcategory')),
            ],
            options={
                'verbose_name': 'Help Article',
                'verbose_name_plural': 'Help Articles',
                'ordering': ['category__sort_order', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_helpful', models.BooleanField()),
                ('comment', models.TextField(blank=True, default='', help_text="Diisi pembaca yang menjawab 'tidak membantu'.")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='helpcenter.helparticle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_article_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help Article Feedback',
                'verbose_name_plural': 'Help Article Feedback',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('article', 'user'), name='uniq_active_help_feedback_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='helpcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_helpcenter_helpcategory_code'),
        ),
        migrations.AddConstraint(
            model_name='helparticle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_help_article_code'),
        ),
        migrations.AddConstraint(
            model_name='helparticle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('slug',), name='uniq_active_help_article_slug'),
        ),
    ]
