# Generated by Django 6.0.6 on 2026-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalaction',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='source',
            field=models.CharField(choices=[('reports_to', 'Direct Supervisor'), ('position', 'Position Hierarchy'), ('department_manager', 'Department Manager'), ('role', 'Role Holder')], default='reports_to', max_length=30),
        ),
    ]
