# Generated by Django 6.0.6 on 2026-08-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_alter_approvalaction_decision_and_more'),
        # Datanya harus sudah dipindah ke engine baru sebelum tabel
        # lamanya dibuang. Tanpa dependency ini urutannya ditentukan
        # abjad nama app, dan `workflow` jatuh setelah `framework` —
        # tiga pengajuan Travel Request yang sedang berjalan akan
        # terhapus tanpa sempat dipindahkan.
        ('workflow', '0002_migrate_framework_approval'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalaction',
            name='uniq_active_framework_approval_action',
        ),
        migrations.RemoveConstraint(
            model_name='approvalflow',
            name='uniq_active_framework_approval_flow',
        ),
        migrations.RemoveIndex(
            model_name='approvalrequest',
            name='idx_approval_request_document',
        ),
        migrations.RemoveIndex(
            model_name='approvalrequest',
            name='idx_approval_request_status',
        ),
        migrations.RemoveConstraint(
            model_name='approvalrequest',
            name='uniq_active_framework_approval_request',
        ),
        migrations.RemoveConstraint(
            model_name='approvalstep',
            name='uniq_active_framework_approval_step',
        ),
        migrations.RemoveField(
            model_name='approvalflow',
            name='company',
        ),
        migrations.RemoveField(
            model_name='approvalflow',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='approvalflow',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='approvalflow',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='subject_employee',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='fallback_role',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='role',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ApprovalAction',
        ),
        migrations.DeleteModel(
            name='ApprovalRequest',
        ),
        migrations.DeleteModel(
            name='ApprovalFlow',
        ),
        migrations.DeleteModel(
            name='ApprovalStep',
        ),
    ]
