# Generated by Django 6.0.6 on 2026-08-10 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_user_roles'),
        ('administration', '0020_remove_workflowapproval_master_work_status_2a3354_idx_and_more'),
        ('hr', '0026_alter_travelarrangement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('module', models.CharField(db_index=True, help_text='Modul pemilik dokumen, mis. hr, payroll, finance, scm.', max_length=100)),
                ('document_type', models.CharField(db_index=True, help_text='Jenis dokumen yang dilayani alur ini, mis. leave_request atau travel_request.', max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='draft', help_text='Hanya alur berstatus Active yang dipakai saat dokumen diajukan.', max_length=20)),
                ('branch', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua branch.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='administration.branch')),
                ('company', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua company yang tidak punya alurnya sendiri.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee_group', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua golongan pegawai.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='administration.employeegroup')),
                ('location', models.ForeignKey(blank=True, help_text='Lokasi kerja pengaju. Dikosongkan = berlaku untuk semua lokasi. Ini kolom yang membedakan alur Head Office dari alur site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='administration.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_definition',
                'ordering': ['module', 'document_type', '-version', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.CharField(blank=True, db_index=True, default='', help_text='Dikosongkan = berlaku untuk semua modul.', max_length=100)),
                ('document_type', models.CharField(blank=True, db_index=True, default='', help_text='Dikosongkan = berlaku untuk semua jenis dokumen.', max_length=100)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(help_text='Yang diberi kuasa memutuskan selama periode ini.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_delegations_received', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(help_text='Approver yang berhalangan.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_delegations_given', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_delegation',
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('approver_type', models.CharField(choices=[('user', 'Specific User'), ('role', 'Role Holder'), ('position', 'Position Hierarchy'), ('manager', 'Direct Manager'), ('department_head', 'Department Head')], default='manager', max_length=30)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Berapa tingkat naik untuk tipe berbasis hierarki. 1 = atasan langsung.')),
                ('approval_mode', models.CharField(choices=[('any', 'Any Approver'), ('all', 'All Approvers')], default='any', help_text='Hanya berpengaruh kalau step ini menghasilkan lebih dari satu approver — praktisnya tipe Role Holder.', max_length=20)),
                ('minimum_approvals', models.PositiveIntegerField(default=1, help_text='Berapa persetujuan yang dibutuhkan pada mode Any Approver.')),
                ('can_reject', models.BooleanField(default=True, help_text='Approver step ini boleh menolak dokumen.')),
                ('can_return', models.BooleanField(default=True, help_text='Approver step ini boleh mengembalikan dokumen ke pengaju untuk diperbaiki, tanpa menolaknya.')),
                ('is_required', models.BooleanField(default=True, help_text='Dimatikan: approver yang tidak ketemu membuat step ini dilewati, bukan menggagalkan seluruh pengajuan.')),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Kosong = step selalu jalan. Bentuknya {"field": "total_days", "op": "gte", "value": 5}, atau digabung lewat {"all": [...]} / {"any": [...]}. Dinilai terhadap konteks dokumen saat diajukan.')),
                ('approver_position', models.ForeignKey(blank=True, help_text='Dikosongkan pada tipe Position Hierarchy = berangkat dari jabatan pengaju sendiri, lalu naik sebanyak Level.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='administration.position')),
                ('approver_role', models.ForeignKey(blank=True, help_text='Wajib diisi kalau tipenya Role Holder.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='accounts.role')),
                ('approver_user', models.ForeignKey(blank=True, help_text='Wajib diisi kalau tipenya Specific User.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowdefinition')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fallback_role', models.ForeignKey(blank=True, help_text='Dipakai kalau penelusuran struktur organisasi tidak menemukan siapa pun. Kosong = step-nya gagal, kecuali step ini ditandai tidak wajib.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_step_fallbacks', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_step',
                'ordering': ['definition_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('document_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('document_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('document_label', models.CharField(blank=True, default='', help_text='Ringkasan yang ditampilkan di kotak masuk approver — disalin, bukan dibaca lewat relasi, karena engine ini tidak mengenal model dokumennya.', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Cuplikan nilai dokumen saat diajukan. Inilah yang dinilai `WorkflowStep.condition` — dibekukan supaya syarat sebuah step tidak berubah di tengah jalan gara-gara dokumennya disunting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='administration.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='administration.company')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowdefinition')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='administration.location')),
                ('subject_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='hr.employee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_workflows', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_instances', to='workflow.workflowstep')),
            ],
            options={
                'db_table': 'workflow_instance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_type', models.CharField(blank=True, choices=[('user', 'Specific User'), ('role', 'Role Holder'), ('position', 'Position Hierarchy'), ('manager', 'Direct Manager'), ('department_head', 'Department Head'), ('fallback_role', 'Fallback Role')], default='', max_length=30)),
                ('assignment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, help_text='Kosong = approver tidak berhasil ditemukan.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_approvals', to=settings.AUTH_USER_MODEL)),
                ('approver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_approvals', to='hr.employee')),
                ('acted_via_delegation', models.ForeignKey(blank=True, help_text='Surat kuasa yang dipakai. Terisi hanya kalau yang memutuskan bukan approver-nya sendiri.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='workflow.workflowdelegation')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflow.workflowinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='workflow.workflowstep')),
            ],
            options={
                'db_table': 'workflow_approval',
                'ordering': ['instance_id', 'sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['module', 'document_type', 'status'], name='idx_workflow_def_target'),
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_workflow_definition_code'),
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('module', 'document_type', 'company', 'branch', 'location', 'employee_group', 'version'), name='uniq_active_workflow_definition_scope'),
        ),
        migrations.AddIndex(
            model_name='workflowdelegation',
            index=models.Index(fields=['delegator', 'starts_at', 'ends_at'], name='idx_workflow_del_active'),
        ),
        migrations.AddIndex(
            model_name='workflowdelegation',
            index=models.Index(fields=['delegate'], name='idx_workflow_del_delegate'),
        ),
        migrations.AddIndex(
            model_name='workflowdelegation',
            index=models.Index(fields=['module', 'document_type'], name='idx_workflow_del_scope'),
        ),
        migrations.AddConstraint(
            model_name='workflowdelegation',
            constraint=models.CheckConstraint(condition=models.Q(('delegator', models.F('delegate')), _negated=True), name='ck_workflow_delegation_different_users'),
        ),
        migrations.AddConstraint(
            model_name='workflowdelegation',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_workflow_delegation_valid_period'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['definition', 'sequence'], name='idx_workflow_step_flow'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('definition', 'sequence'), name='uniq_active_workflow_step_sequence'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['module', 'document_type', 'object_id'], name='idx_workflow_inst_target'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'created_at'], name='idx_workflow_inst_status'),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'pending', 'returned'])), fields=('module', 'document_type', 'object_id'), name='uq_workflow_open_instance'),
        ),
        migrations.AddIndex(
            model_name='workflowapproval',
            index=models.Index(fields=['approver', 'status', 'created_at'], name='idx_workflow_approval_inbox'),
        ),
        migrations.AddIndex(
            model_name='workflowapproval',
            index=models.Index(fields=['instance', 'step', 'status'], name='idx_workflow_approval_step'),
        ),
        migrations.AddConstraint(
            model_name='workflowapproval',
            constraint=models.UniqueConstraint(fields=('instance', 'step', 'approver'), name='uq_workflow_approval_instance_step_approver'),
        ),
    ]
