# Generated by Django 6.0.6 on 2026-08-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_migrate_framework_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='approver_scope',
            field=models.CharField(choices=[('tenant', 'Seluruh Tenant'), ('company', 'Company'), ('branch', 'Branch'), ('location', 'Location'), ('division', 'Division'), ('department', 'Department'), ('section', 'Section')], default='company', help_text='Sejauh mana pemegang role dicari, dibandingkan dengan penempatan pegawai yang dokumennya diproses. Hanya berpengaruh untuk tipe Role Holder dan role cadangan. Pilih Location untuk meja yang memang per site (KTT, Admin Site), Company untuk yang melayani lintas site (HRGA, HR Manager).', max_length=20),
        ),
    ]
