# Generated by Django 6.0.6 on 2026-08-12 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_data_scope_level_role_data_scope_mode_and_more'),
        ('workflow', '0003_workflowstep_approver_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepFallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Urutan pencarian; yang terkecil dicoba lebih dulu.')),
                ('approver_scope', models.CharField(choices=[('tenant', 'Seluruh Tenant'), ('company', 'Company'), ('branch', 'Branch'), ('location', 'Location'), ('division', 'Division'), ('department', 'Department'), ('section', 'Section')], default='company', help_text='Sejauh mana pemegang role cadangan ini dicari. Company untuk jaring terakhir; Department atau Section untuk turunan yang memang harus tetap di unit pegawainya.', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_step_fallback_links', to='accounts.role')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallbacks', to='workflow.workflowstep')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_step_fallback',
                'ordering': ['step', 'sequence'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('step', 'sequence'), name='uniq_active_workflow_step_fallback_sequence')],
            },
        ),
    ]
