# Generated by Django 6.0.6 on 2026-08-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_workflowstepfallback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowapproval',
            name='assignment_reference',
            field=models.TextField(blank=True, default=''),
        ),
    ]
