# Generated by Django 6.0.6 on 2026-08-02 16:07

import apps.uploads.models.uploaded_file
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(max_length=500, upload_to=apps.uploads.models.uploaded_file.uploaded_file_path)),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.uploads.models.uploaded_file.uploaded_thumbnail_path)),
                ('original_name', models.CharField(db_index=True, max_length=255)),
                ('stored_name', models.CharField(blank=True, max_length=255)),
                ('extension', models.CharField(blank=True, db_index=True, max_length=30)),
                ('mime_type', models.CharField(blank=True, db_index=True, max_length=150)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('archive', 'Archive'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='ready', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploads_uploaded_file',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_deleted'], name='upload_status_deleted_idx'), models.Index(fields=['file_type', 'created_at'], name='upload_type_created_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='upload_user_created_idx')],
            },
        ),
    ]
