# Generated by Django 6.0.6 on 2026-08-03 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('attachment', 'Attachment'), ('avatar', 'Avatar'), ('signature', 'Signature'), ('import', 'Import'), ('export', 'Export'), ('report', 'Report'), ('temporary', 'Temporary')], db_index=True, default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='last_download_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['category', 'created_at'], name='upload_category_created_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['expires_at', 'is_deleted'], name='upload_expiry_deleted_idx'),
        ),
    ]
