# Generated by Django 6.0.6 on 2026-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_uploadedfile_category_uploadedfile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('attachment', 'Attachment'), ('content', 'Content'), ('avatar', 'Avatar'), ('signature', 'Signature'), ('import', 'Import'), ('export', 'Export'), ('report', 'Report'), ('temporary', 'Temporary')], db_index=True, default='general', max_length=30),
        ),
    ]
