# Generated by Django 6.0.6 on 2026-10-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_uploadedfile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('attachment', 'Attachment'), ('content', 'Content'), ('avatar', 'Avatar'), ('attendance_selfie', 'Attendance Selfie'), ('signature', 'Signature'), ('import', 'Import'), ('export', 'Export'), ('report', 'Report'), ('temporary', 'Temporary')], db_index=True, default='general', max_length=30),
        ),
    ]
