# Generated by Django 6.0.6 on 2026-07-26 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_shift_workschedule_workscheduleday_and_more'),
        ('hr', '0001_initial'),
        ('payroll', '0002_allowancetemplate_deductiontemplate_overtimegroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Migrasi ini menambah FK ke `administration.Site`, model yang
    # dihapus oleh `administration.0011_rename_site_to_location`.
    # Tanpa pernyataan urutan ini, Django bebas menjadwalkan rename lebih
    # dulu — dan replay dari nol gagal dengan
    # "Related model 'administration.site' cannot be resolved".
    #
    # Database yang sudah termigrasi tidak terpengaruh: Django cuma
    # mencatat nama migrasi, bukan isinya. Yang diperbaiki adalah
    # penyediaan tenant baru dan pembuatan database uji.
    run_before = [
        ("administration", "0011_rename_site_to_location"),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('join_date', models.DateField()),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('probation_start', models.DateField(blank=True, null=True)),
                ('probation_end', models.DateField(blank=True, null=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('employment_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='hr.employee')),
                ('employment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.employmentstatus')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.employmenttype')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.shift')),
                ('termination_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.terminationreason')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.workschedule')),
                ('working_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.workcalendar')),
            ],
            options={
                'db_table': 'hr_employee_employment',
                'ordering': ['employee__employee_number'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('organization_effective_date', models.DateField()),
                ('organization_notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_organizations', to='administration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_organizations', to='administration.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_organizations', to='administration.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_organizations', to='administration.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_organizations', to='administration.division')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='hr.employee')),
                ('job_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_organizations', to='administration.grade')),
                ('job_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_organizations', to='administration.joblevel')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_organizations', to='administration.position')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hr.employee')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_organizations', to='administration.section')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_organizations', to='administration.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee_organization',
            },
        ),
        migrations.CreateModel(
            name='PayrollAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='bank_transfer', max_length=30)),
                ('tax_number_payroll', models.CharField(blank=True, max_length=50)),
                ('bpjs_kesehatan_number', models.CharField(blank=True, max_length=50)),
                ('bpjs_ketenagakerjaan_number', models.CharField(blank=True, max_length=50)),
                ('overtime_eligible', models.BooleanField(default=False)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('payroll_notes', models.TextField(blank=True)),
                ('allowance_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_payroll_assignments', to='payroll.allowancetemplate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_payroll_assignments', to='administration.currency')),
                ('deduction_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_payroll_assignments', to='payroll.deductiontemplate')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_assignments', to='hr.employee')),
                ('overtime_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_payroll_assignments', to='payroll.overtimegroup')),
                ('payroll_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_payroll_assignments', to='payroll.payrollgroup')),
                ('salary_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_payroll_assignments', to='payroll.salarygrade')),
                ('salary_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_payroll_assignments', to='payroll.salarylevel')),
                ('tax_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_payroll_assignments', to='payroll.taxstatus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee_payroll_assignment',
                'ordering': ['employee_id', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'effective_from'), name='uniq_employee_payroll_assignment_effective_from'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('employee',), name='uniq_current_employee_payroll_assignment')],
            },
        ),
    ]
