# Generated by Django 6.0.6 on 2026-07-27 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_rename_grade_jobgrade_alter_jobgrade_table'),
        ('hr', '0002_employmentassignment_organizationassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentassignment',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.contracttype'),
        ),
        migrations.AddField(
            model_name='employmentassignment',
            name='employee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.employeegroup'),
        ),
        migrations.AddField(
            model_name='employmentassignment',
            name='probation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.probationtype'),
        ),
    ]
