# Generated by Django 6.0.6 on 2026-07-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='preferred_name',
        ),
    ]
