# Generated by Django 6.0.6 on 2026-08-03 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_documenttype_allow_multiple_documenttype_category_and_more'),
        ('hr', '0007_employeebankaccount_employeecertificate_and_more'),
        ('uploads', '0002_uploadedfile_category_uploadedfile_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecertificate',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='employeemedicalevent',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='employeetraining',
            name='attachment',
        ),
        migrations.AddField(
            model_name='employeecertificate',
            name='uploaded_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uploads.uploadedfile'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='uploaded_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uploads.uploadedfile'),
        ),
        migrations.AddField(
            model_name='employeemedicalevent',
            name='uploaded_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uploads.uploadedfile'),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='uploaded_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uploads.uploadedfile'),
        ),
        migrations.AddConstraint(
            model_name='employeebankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee', 'bank', 'account_number'), name='uniq_active_employee_bank_account'),
        ),
    ]
