# Generated by Django 6.0.6 on 2026-08-03 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_documenttype_allow_multiple_documenttype_category_and_more'),
        ('hr', '0008_remove_employeecertificate_attachment_and_more'),
        ('uploads', '0002_uploadedfile_category_uploadedfile_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Migrasi ini menambah FK ke `administration.Site`, model yang
    # dihapus oleh `administration.0011_rename_site_to_location`.
    # Tanpa pernyataan urutan ini, Django bebas menjadwalkan rename lebih
    # dulu — dan replay dari nol gagal dengan
    # "Related model 'administration.site' cannot be resolved".
    #
    # Database yang sudah termigrasi tidak terpengaruh: Django cuma
    # mencatat nama migrasi, bukan isinya. Yang diperbaiki adalah
    # penyediaan tenant baru dan pembuatan database uji.
    run_before = [
        ("administration", "0011_rename_site_to_location"),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('device_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Face Recognition'), ('card', 'RFID / Card'), ('mobile', 'Mobile'), ('web', 'Web'), ('other', 'Other')], default='fingerprint', max_length=30)),
                ('vendor', models.CharField(blank=True, default='', max_length=150)),
                ('model_name', models.CharField(blank=True, default='', max_length=150)),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                ('integration_key', models.CharField(blank=True, default='', max_length=255)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_devices', to='administration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_devices', to='administration.company')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_devices', to='administration.site')),
            ],
            options={
                'db_table': 'hr_attendance_device',
                'ordering': ['company_id', 'site_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('leave', 'Leave'), ('sick', 'Sick'), ('permit', 'Permit'), ('business_trip', 'Business Trip'), ('remote', 'Remote Work'), ('holiday', 'Holiday'), ('day_off', 'Day Off'), ('incomplete', 'Incomplete')], db_index=True, default='present', max_length=30)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('device', 'Attendance Device'), ('mobile', 'Mobile'), ('web', 'Web'), ('import', 'Import'), ('api', 'API'), ('system', 'System')], db_index=True, default='manual', max_length=20)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('scheduled_check_in', models.DateTimeField(blank=True, null=True)),
                ('scheduled_check_out', models.DateTimeField(blank=True, null=True)),
                ('check_in', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_check_in', models.DateTimeField(blank=True, null=True)),
                ('last_check_out', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_leave_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_address', models.CharField(blank=True, default='', max_length=500)),
                ('check_out_address', models.CharField(blank=True, default='', max_length=500)),
                ('is_geofence_valid', models.BooleanField(default=True)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('device_code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('import_batch_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('is_manual_adjustment', models.BooleanField(default=False)),
                ('adjustment_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employee_attendances', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_attendances', to='administration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_attendances', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_attendances', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_employee_attendances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='hr.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendances', to='administration.shift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_attendances', to='administration.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employee_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee_attendance',
                'ordering': ['-work_date', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('log_type', models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out'), ('break_in', 'Break In'), ('break_out', 'Break Out'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('device', 'Attendance Device'), ('mobile', 'Mobile'), ('web', 'Web'), ('import', 'Import'), ('api', 'API'), ('system', 'System')], db_index=True, default='device', max_length=20)),
                ('employee_identifier', models.CharField(blank=True, db_index=True, default='', help_text='Employee number, PIN, card number, or external machine identifier.', max_length=150)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('import_batch_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='administration.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_logs', to='administration.company')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='hr.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_logs', to='hr.employee')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_log_photos', to='uploads.uploadedfile')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='administration.site')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='hr.employeeattendance')),
            ],
            options={
                'db_table': 'hr_attendance_log',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['company', 'work_date'], name='idx_hr_att_company_date'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['site', 'work_date'], name='idx_hr_att_site_date'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['employee', 'work_date', 'status'], name='idx_hr_att_emp_date_status'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['source', 'external_id'], name='idx_hr_att_source_external'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee', 'work_date'), name='uq_hr_attendance_employee_work_date_active'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee', 'occurred_at'], name='idx_hr_att_log_emp_time'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['device', 'occurred_at'], name='idx_hr_att_log_device_time'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['company', 'site', 'occurred_at'], name='idx_hr_att_log_org_time'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['is_processed', 'occurred_at'], name='idx_hr_att_log_process_time'),
        ),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='uq_hr_att_log_source_external'),
        ),
    ]
