# Generated by Django 6.0.6 on 2026-08-05 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_documenttype_allow_multiple_documenttype_category_and_more'),
        ('hr', '0009_attendancedevice_employeeattendance_attendancelog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Migrasi ini menambah FK ke `administration.Site`, model yang
    # dihapus oleh `administration.0011_rename_site_to_location`.
    # Tanpa pernyataan urutan ini, Django bebas menjadwalkan rename lebih
    # dulu — dan replay dari nol gagal dengan
    # "Related model 'administration.site' cannot be resolved".
    #
    # Database yang sudah termigrasi tidak terpengaruh: Django cuma
    # mencatat nama migrasi, bukan isinya. Yang diperbaiki adalah
    # penyediaan tenant baru dan pembuatan database uji.
    run_before = [
        ("administration", "0011_rename_site_to_location"),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('encoding', models.CharField(default='utf-8-sig', max_length=50)),
                ('mapping', models.JSONField(default=dict)),
                ('value_mapping', models.JSONField(blank=True, default=dict)),
                ('datetime_formats', models.JSONField(blank=True, default=list)),
                ('defaults', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_import_profiles', to='administration.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_import_profiles', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_import_profiles', to='administration.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='hr.attendanceimportprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
