# Generated by Django 6.0.6 on 2026-08-07 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_documenttype_allow_multiple_documenttype_category_and_more'),
        ('hr', '0010_attendanceimportprofile_attendanceimportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee_number',), name='uniq_active_employee_number'),
        ),
    ]
