# Generated by Django 6.0.6 on 2026-08-07 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_attendancestatus_code_alter_bank_code_and_more'),
        ('hr', '0011_alter_employee_employee_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceimportprofile',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='attendanceimportprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_hr_attendanceimportprofile_code'),
        ),
    ]
