# Generated by Django 6.0.6 on 2026-08-08 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_remove_holiday_uniq_core_holiday_company_site_date_and_more'),
        ('hr', '0013_rename_site_to_location'),
        ('uploads', '0002_uploadedfile_category_uploadedfile_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancedevice',
            options={'ordering': ['company_id', 'location_id', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='attendancelog',
            name='idx_hr_att_log_org_time',
        ),
        migrations.RemoveIndex(
            model_name='employeeattendance',
            name='idx_hr_att_site_date',
        ),
        migrations.AlterField(
            model_name='attendancedevice',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_devices', to='administration.location'),
        ),
        migrations.AlterField(
            model_name='attendanceimportprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_import_profiles', to='administration.location'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='administration.location'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_attendances', to='administration.location'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['company', 'location', 'occurred_at'], name='idx_hr_att_log_org_time'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['location', 'work_date'], name='idx_hr_att_location_date'),
        ),
    ]
