# Generated by Django 6.0.6 on 2026-08-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_remove_holiday_uniq_core_holiday_company_site_date_and_more'),
        ('hr', '0014_alter_attendancedevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentassignment',
            name='job_location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employmentassignment',
            name='employment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.employmentstatus'),
        ),
        migrations.AlterField(
            model_name='employmentassignment',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.employmenttype'),
        ),
    ]
