# Generated by Django 6.0.6 on 2026-08-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_rostercrew'),
        ('hr', '0016_jobvacancy_candidate_leavebalance_trainingprogram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentassignment',
            name='roster_crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.rostercrew'),
        ),
        migrations.AddField(
            model_name='employmentassignment',
            name='roster_start_override',
            field=models.DateField(blank=True, null=True),
        ),
    ]
