# Generated by Django 6.0.6 on 2026-08-08 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_accommodationtype_transportmode'),
        ('hr', '0017_employmentassignment_roster_crew_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cycle_work_days', models.PositiveSmallIntegerField(blank=True, help_text='Jumlah hari blok kerja, mis. 42 untuk 6 minggu.', null=True)),
                ('cycle_off_days', models.PositiveSmallIntegerField(blank=True, help_text='Jumlah hari blok off, mis. 14 untuk 2 minggu.', null=True)),
                ('start_date', models.DateField(help_text='Hari pertama blok kerja pada siklus pertama.')),
                ('cycle_count', models.PositiveSmallIntegerField(default=4)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_rotations', to='administration.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_rotations', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_rotations', to='hr.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_rotations', to='administration.location')),
                ('roster_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_rotations', to='administration.rostercrew')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_site_rotation',
                'ordering': ['-start_date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='RotationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('period_type', models.CharField(choices=[('work', 'On Site'), ('off', 'Off')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_periods', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='hr.siterotation')),
            ],
            options={
                'db_table': 'hr_rotation_period',
                'ordering': ['rotation', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='RotationTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('in', 'Travel In'), ('out', 'Travel Out')], max_length=10)),
                ('travel_start_date', models.DateField()),
                ('travel_end_date', models.DateField(blank=True, help_text='Dikosongkan = tiba di hari yang sama.', null=True)),
                ('origin', models.CharField(blank=True, default='', help_text='Titik berangkat, mis. Jakarta.', max_length=150)),
                ('destination', models.CharField(blank=True, default='', help_text='Titik tujuan, mis. Gebe.', max_length=150)),
                ('transport_detail', models.CharField(blank=True, default='', help_text='Nomor penerbangan, nama kapal, atau rute etape. Mis. GA-642 / KM Sabuk Nusantara.', max_length=200)),
                ('ticket_number', models.CharField(blank=True, default='', max_length=100)),
                ('accommodation_needed', models.BooleanField(default=False)),
                ('accommodation_name', models.CharField(blank=True, default='', help_text='Nama hotel/mess, mis. Hotel Bukit Pelangi.', max_length=150)),
                ('accommodation_checkin', models.DateField(blank=True, null=True)),
                ('accommodation_checkout', models.DateField(blank=True, null=True)),
                ('accommodation_nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('accommodation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotation_travels', to='administration.accommodationtype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='hr.rotationperiod')),
                ('transport_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotation_travels', to='administration.transportmode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_rotation_travel',
                'ordering': ['period', 'direction', 'travel_start_date'],
                'indexes': [models.Index(fields=['travel_start_date'], name='idx_rotation_travel_start')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('period', 'direction'), name='uniq_active_hr_rotation_travel_direction')],
            },
        ),
        migrations.AddIndex(
            model_name='siterotation',
            index=models.Index(fields=['employee'], name='idx_site_rotation_employee'),
        ),
        migrations.AddIndex(
            model_name='siterotation',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_site_rotation_period'),
        ),
        migrations.AddIndex(
            model_name='siterotation',
            index=models.Index(fields=['status'], name='idx_site_rotation_status'),
        ),
        migrations.AddIndex(
            model_name='rotationperiod',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='idx_rotation_period_emp_range'),
        ),
        migrations.AddIndex(
            model_name='rotationperiod',
            index=models.Index(fields=['period_type'], name='idx_rotation_period_type'),
        ),
        migrations.AddConstraint(
            model_name='rotationperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('rotation', 'sequence'), name='uniq_active_hr_rotation_period_sequence'),
        ),
    ]
