# Generated by Django 6.0.6 on 2026-08-08 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_accommodationtype_transportmode'),
        ('hr', '0018_siterotation_rotationperiod_rotationtravel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotationperiod',
            options={'ordering': ['rotation', 'start_date', 'sequence']},
        ),
        migrations.AddField(
            model_name='employmentassignment',
            name='point_of_hire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.city'),
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='employee_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_periods', to='hr.employeeleave'),
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotation_periods', to='administration.leavetype'),
        ),
        migrations.AddField(
            model_name='rotationtravel',
            name='is_special_arrangement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rotationtravel',
            name='justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rotationtravel',
            name='special_arrangement_notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='siterotation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('document_number', ''), _negated=True)), fields=('document_number',), name='uniq_active_hr_site_rotation_number'),
        ),
    ]
