# Generated by Django 6.0.6 on 2026-08-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_rotationpurpose'),
        ('hr', '0019_alter_rotationperiod_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotationperiod',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotation_periods', to='administration.rotationpurpose'),
        ),
        migrations.AddField(
            model_name='rotationtravel',
            name='counts_as_work',
            field=models.BooleanField(default=True),
        ),
    ]
