# Generated by Django 6.0.6 on 2026-08-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_remove_rotationperiod_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotationtravel',
            options={'ordering': ['period__start_date', 'period__sequence', 'direction', 'travel_start_date']},
        ),
        migrations.AddField(
            model_name='rotationtravel',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='cycle_travel_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Hari perjalanan sekali jalan, di luar Work Days dan Off Days. 0 = travel dianggap masuk blok kerja.'),
        ),
    ]
