# Generated by Django 6.0.6 on 2026-08-09 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_rotationpurpose'),
        ('hr', '0021_alter_rotationtravel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('out', 'Keberangkatan'), ('in', 'Kepulangan')], max_length=10)),
                ('travel_start_date', models.DateField()),
                ('travel_end_date', models.DateField(blank=True, help_text='Dikosongkan = tiba di hari yang sama.', null=True)),
                ('origin', models.CharField(blank=True, default='', help_text='Titik berangkat, mis. Gebe.', max_length=150)),
                ('destination', models.CharField(blank=True, default='', help_text='Titik tujuan, mis. Jakarta.', max_length=150)),
                ('transport_detail', models.CharField(blank=True, default='', help_text='Nomor penerbangan, nama kapal, atau rute etape. Mis. GA-642 / KM Sabuk Nusantara.', max_length=200)),
                ('ticket_number', models.CharField(blank=True, default='', max_length=100)),
                ('justification', models.TextField(blank=True, default='', help_text='Alasan perjalanan ini menyimpang dari rotasi normal. Kosong = perjalanan rutin.')),
                ('is_special_arrangement', models.BooleanField(default=False)),
                ('special_arrangement_notes', models.CharField(blank=True, default='', max_length=200)),
                ('accommodation_needed', models.BooleanField(default=False)),
                ('accommodation_name', models.CharField(blank=True, default='', help_text='Nama hotel/mess, mis. Hotel Bukit Pelangi.', max_length=150)),
                ('accommodation_checkin', models.DateField(blank=True, null=True)),
                ('accommodation_checkout', models.DateField(blank=True, null=True)),
                ('accommodation_nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('counts_as_work', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'hr_travel_arrangement',
                'ordering': ['request', 'direction', 'travel_start_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'hr_travel_request',
                'ordering': ['-start_date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='TravelRequestPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'hr_travel_request_purpose',
                'ordering': ['request', 'start_date', 'sequence'],
            },
        ),
        migrations.RemoveIndex(
            model_name='rotationtravel',
            name='idx_rotation_travel_start',
        ),
        migrations.RemoveConstraint(
            model_name='rotationtravel',
            name='uniq_active_hr_rotation_travel_direction',
        ),
        migrations.AddField(
            model_name='travelarrangement',
            name='accommodation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_arrangements', to='administration.accommodationtype'),
        ),
        migrations.AddField(
            model_name='travelarrangement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelarrangement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelarrangement',
            name='transport_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_arrangements', to='administration.transportmode'),
        ),
        migrations.AddField(
            model_name='travelarrangement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='administration.branch'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='administration.company'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='administration.location'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='rotation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_requests', to='hr.rotationperiod'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelarrangement',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='hr.travelrequest'),
        ),
        migrations.AddField(
            model_name='travelrequestpurpose',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequestpurpose',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequestpurpose',
            name='employee_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_request_purposes', to='hr.employeeleave'),
        ),
        migrations.AddField(
            model_name='travelrequestpurpose',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_request_purposes', to='administration.rotationpurpose'),
        ),
        migrations.AddField(
            model_name='travelrequestpurpose',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to='hr.travelrequest'),
        ),
        migrations.AddField(
            model_name='travelrequestpurpose',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='rotationtravel',
            name='accommodation_type',
        ),
        migrations.RemoveField(
            model_name='rotationtravel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rotationtravel',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='rotationtravel',
            name='period',
        ),
        migrations.RemoveField(
            model_name='rotationtravel',
            name='transport_mode',
        ),
        migrations.RemoveField(
            model_name='rotationtravel',
            name='updated_by',
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['employee', 'start_date'], name='idx_travel_request_emp_date'),
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['status'], name='idx_travel_request_status'),
        ),
        migrations.AddConstraint(
            model_name='travelrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('document_number', ''), _negated=True)), fields=('document_number',), name='uniq_active_hr_travel_request_number'),
        ),
        migrations.AddIndex(
            model_name='travelarrangement',
            index=models.Index(fields=['travel_start_date'], name='idx_travel_arrangement_start'),
        ),
        migrations.AddConstraint(
            model_name='travelarrangement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('request', 'direction'), name='uniq_active_hr_travel_arrangement_direction'),
        ),
        migrations.AddConstraint(
            model_name='travelrequestpurpose',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('request', 'sequence'), name='uniq_active_hr_travel_request_purpose'),
        ),
        migrations.DeleteModel(
            name='RotationTravel',
        ),
    ]
