# Generated by Django 6.0.6 on 2026-08-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_travelarrangement_travelrequest_travelrequestpurpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentassignment',
            name='travel_days_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Hari perjalanan sekali jalan khusus pegawai ini. Kosongkan untuk ikut aturan (site, Point of Hire).', null=True),
        ),
    ]
