# Generated by Django 6.0.6 on 2026-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_employmentassignment_travel_days_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelarrangement',
            name='direction',
            field=models.CharField(choices=[('out', 'Outbound'), ('in', 'Inbound')], max_length=10),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
