# Generated by Django 6.0.6 on 2026-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_alter_travelarrangement_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siterotation',
            name='cycle_travel_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total hari perjalanan pulang-pergi, di luar Work Days dan Off Days. 2 = sehari keluar, sehari kembali. Angka ganjil condong ke sisi keluar (3 = 2 keluar, 1 kembali). 0 = travel dianggap masuk blok kerja.'),
        ),
    ]
