# Generated by Django 6.0.6 on 2026-08-09 16:47

from django.conf import settings
from django.db import migrations, models


def backfill_sequence(apps, schema_editor):
    """
    Baris lama = satu-satunya etape di arahnya, jadi nomor 1.

    Dibiarkan NULL pun constraint-nya tidak protes (NULL dianggap
    berbeda satu sama lain di Postgres), tapi kolom kosong di grid
    membuat pengisi berikutnya mengira nomornya memang tidak dipakai.
    """
    TravelArrangement = apps.get_model("hr", "TravelArrangement")

    TravelArrangement.objects.filter(sequence__isnull=True).update(
        sequence=1,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_alter_rosterpolicy_default_travel_days_and_more'),
        ('hr', '0025_alter_siterotation_cycle_travel_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelarrangement',
            options={'ordering': ['request', 'travel_start_date', 'direction', 'sequence']},
        ),
        migrations.RemoveConstraint(
            model_name='travelarrangement',
            name='uniq_active_hr_travel_arrangement_direction',
        ),
        migrations.AddField(
            model_name='travelarrangement',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Urutan etape dalam satu arah. 1 = Jakarta → Sorong, 2 = Sorong → Gebe.', null=True),
        ),
        migrations.RunPython(
            backfill_sequence,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='travelarrangement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('request', 'direction', 'sequence'), name='uniq_active_hr_travel_arrangement_leg'),
        ),
    ]
