# Generated by Django 6.0.6 on 2026-08-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_alter_travelarrangement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
