# Generated by Django 6.0.6 on 2026-08-11 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_employeeleave_document_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReminderPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='Default', max_length=100)),
                ('probation_enabled', models.BooleanField(default=True, help_text='Ingatkan masa percobaan yang akan berakhir.')),
                ('probation_lead_days', models.PositiveSmallIntegerField(default=14, help_text='Berapa hari sebelum masa percobaan berakhir pengingatnya mulai muncul.')),
                ('contract_enabled', models.BooleanField(default=True, help_text='Ingatkan kontrak kerja yang akan berakhir.')),
                ('contract_lead_days', models.PositiveSmallIntegerField(default=30, help_text='Berapa hari sebelum kontrak berakhir pengingatnya mulai muncul. Umumnya lebih panjang dari masa percobaan karena perpanjangan kontrak butuh persetujuan berlapis.')),
                ('birthday_enabled', models.BooleanField(default=True, help_text='Ingatkan ulang tahun pegawai.')),
                ('birthday_lead_days', models.PositiveSmallIntegerField(default=7, help_text='Berapa hari sebelum ulang tahun pengingatnya muncul.')),
                ('anniversary_enabled', models.BooleanField(default=False, help_text='Ingatkan hari jadi kerja (ulang tahun masa kerja). Dimatikan secara bawaan — tidak semua perusahaan memperingatinya.')),
                ('anniversary_lead_days', models.PositiveSmallIntegerField(default=7, help_text='Berapa hari sebelum hari jadi kerja pengingatnya muncul.')),
                ('keep_overdue_days', models.PositiveSmallIntegerField(default=30, help_text='Berapa lama tanggal yang sudah lewat tetap ditampilkan. Nol berarti langsung hilang begitu tanggalnya lewat — dan kontrak yang terlewat justru itu yang paling perlu terlihat, karena pegawainya masih bekerja tanpa dasar.')),
                ('is_default', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee_reminder_policy',
                'ordering': ['name'],
            },
        ),
    ]
