# Generated by Django 6.0.6 on 2026-08-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_employeereminderpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereminderpolicy',
            name='notify_employee',
            field=models.BooleanField(default=False, help_text='Kirim juga ke pegawai yang bersangkutan, untuk masa percobaan dan kontrak saja. Ulang tahun tidak pernah dikirim ke orangnya sendiri.'),
        ),
        migrations.AddField(
            model_name='employeereminderpolicy',
            name='notify_hr',
            field=models.BooleanField(default=True, help_text='Kirim pengingat ke pemegang role HR. Yang diterima masing-masing tetap dibatasi cakupan datanya — admin site tidak menerima pengingat pegawai kantor pusat.'),
        ),
    ]
