# Generated by Django 6.0.6 on 2026-08-11 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_employmenttype_requires_contract'),
        ('hr', '0029_employeereminderpolicy_notify_employee_and_more'),
        ('payroll', '0003_alter_allowancetemplate_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('action_type', models.CharField(choices=[('contract_extension', 'Contract Extension'), ('contract_change', 'Contract Change'), ('employment_type_change', 'Employment Type Change'), ('probation_change', 'Probation Change'), ('status_change', 'Employment Status Change'), ('transfer', 'Transfer'), ('promotion', 'Promotion'), ('demotion', 'Demotion'), ('position_change', 'Position Change'), ('salary_change', 'Salary Change'), ('resignation', 'Resignation'), ('termination', 'Termination')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Pending Approval'), ('approved', 'Approved'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('proposed_contract_start', models.DateField(blank=True, null=True)),
                ('proposed_contract_end', models.DateField(blank=True, null=True)),
                ('proposed_probation_start', models.DateField(blank=True, null=True)),
                ('proposed_probation_end', models.DateField(blank=True, null=True)),
                ('proposed_basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('values_before', models.JSONField(blank=True, default=dict)),
                ('values_after', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_error', models.TextField(blank=True, default='')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_employee_actions', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='administration.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='hr.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='administration.location')),
                ('proposed_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.branch')),
                ('proposed_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.company')),
                ('proposed_contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='administration.contracttype')),
                ('proposed_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.costcenter')),
                ('proposed_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.department')),
                ('proposed_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.division')),
                ('proposed_employee_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='administration.employeegroup')),
                ('proposed_employment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='administration.employmentstatus')),
                ('proposed_employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='administration.employmenttype')),
                ('proposed_job_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.jobgrade')),
                ('proposed_job_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.joblevel')),
                ('proposed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.location')),
                ('proposed_payroll_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='payroll.payrollgroup')),
                ('proposed_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.position')),
                ('proposed_probation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='administration.probationtype')),
                ('proposed_reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.employee')),
                ('proposed_salary_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='payroll.salarygrade')),
                ('proposed_salary_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='payroll.salarylevel')),
                ('proposed_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.section')),
                ('termination_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_actions', to='administration.terminationreason')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee_action',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'effective_date'], name='idx_emp_action_emp_date'), models.Index(fields=['action_type', 'status'], name='idx_emp_action_type_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('document_number', ''), _negated=True)), fields=('document_number',), name='uniq_active_hr_employee_action_number')],
            },
        ),
    ]
