# Generated by Django 6.0.6 on 2026-08-12 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_backfill_legacy_contract_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaction',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Yang mengusulkan perubahan ini. Dikosongkan = yang membuat dokumennya sendiri yang mengusulkan.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_actions', to='hr.employee'),
        ),
    ]
