# Generated by Django 6.0.6 on 2026-08-12 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_roster_policy_cycle_pattern'),
        ('hr', '0032_employeeaction_requested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentassignment',
            name='back_to_back_partner',
            field=models.ForeignKey(blank=True, help_text='Pegawai yang masuk saat orang ini off. Opsional — tidak pernah menghalangi jadwal disetujui.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_to_back_of', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employmentassignment',
            name='roster_cycle_start',
            field=models.DateField(blank=True, help_text='Current Cycle Start pegawai ini. Artinya mengikuti Cycle Start Basis pada Roster Policy-nya. Boleh tanggal lampau — jadwal berangkat dari blok yang sedang dijalani.', null=True),
        ),
        migrations.AddField(
            model_name='employmentassignment',
            name='roster_policy',
            field=models.ForeignKey(blank=True, help_text='Pola roster pegawai ini (6:2, 8:2, …). Dikosongkan = pegawai non-roster, tidak diproses Roster Generator.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_employments', to='administration.rosterpolicy'),
        ),
        migrations.AddField(
            model_name='employmentassignment',
            name='roster_start_basis',
            field=models.CharField(blank=True, default='', help_text='Menimpa Cycle Start Basis milik policy untuk pegawai ini saja. Dikosongkan = ikut policy.', max_length=20),
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='counts_as_roster_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='cycle_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='segment_type',
            field=models.CharField(choices=[('work', 'On Site'), ('field_break', 'Field Break'), ('travel_out', 'Travel Out'), ('travel_in', 'Travel In')], db_index=True, default='work', max_length=20),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='cycle_start',
            field=models.DateField(blank=True, help_text='Current Cycle Start yang dibekukan ke rencana ini.', null=True),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Kosong = era berjalan.', null=True),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='horizon_end',
            field=models.DateField(blank=True, help_text='Sampai kapan segmen sudah digenerate.', null=True),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Saat baseline dikunci. Sesudah ini jadwal hanya berubah lewat dokumen Adjustment.', null=True),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='roster_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_plans', to='administration.rosterpolicy'),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='roster_start_basis',
            field=models.CharField(blank=True, default='work_start', max_length=20),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='travel_creates_segment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='travel_day_mode',
            field=models.CharField(blank=True, default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='travel_in_counts_as_roster_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='travel_in_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='travel_out_counts_as_roster_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='travel_out_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rotationperiod',
            name='period_type',
            field=models.CharField(choices=[('work', 'On Site'), ('off', 'Off')], help_text='Turunan dari Segment Type — diisi service, jangan diketik.', max_length=10),
        ),
        migrations.AlterField(
            model_name='siterotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('planned', 'Planned (legacy)')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='RosterPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version_no', models.PositiveSmallIntegerField()),
                ('source', models.CharField(choices=[('initial', 'Initial Baseline'), ('adjustment', 'Operational Adjustment'), ('policy_change', 'Policy Change'), ('horizon_extension', 'Horizon Extension'), ('correction', 'Correction')], default='initial', max_length=30)),
                ('effective_from', models.DateField(blank=True, help_text='Perubahan berlaku dari tanggal ini ke depan.', null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='hr.siterotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_roster_plan_version',
                'ordering': ['plan', 'version_no'],
            },
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='version_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments_added', to='hr.rosterplanversion'),
        ),
        migrations.AddField(
            model_name='rotationperiod',
            name='version_to',
            field=models.ForeignKey(blank=True, help_text='Kosong = masih berlaku pada versi berjalan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments_closed', to='hr.rosterplanversion'),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='baseline_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_of', to='hr.rosterplanversion'),
        ),
        migrations.AddField(
            model_name='siterotation',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_of', to='hr.rosterplanversion'),
        ),
        migrations.CreateModel(
            name='RosterSetupLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('current_cycle_start', models.DateField(help_text='Boleh tanggal lampau — hari pertama blok yang sedang dijalani pegawai ini sekarang.')),
                ('opening_rotation_credit', models.DecimalField(decimal_places=2, default=0, help_text='Saldo awal rotation credit dari sistem lama.', max_digits=6)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('committed', 'Committed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('commit_error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_setup_lines', to='hr.employee')),
                ('roster_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_setup_lines', to='administration.rosterpolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_roster_setup_line',
                'ordering': ['request', 'employee__employee_number'],
            },
        ),
        migrations.AddField(
            model_name='siterotation',
            name='setup_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='hr.rostersetupline'),
        ),
        migrations.CreateModel(
            name='RosterSetupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('as_of_date', models.DateField(help_text='Keadaan direkam per tanggal ini. Jadwal berangkat dari blok yang sedang dijalani, bukan dari awal riwayat.')),
                ('horizon_months', models.PositiveSmallIntegerField(default=12, help_text='Jadwal digenerate sampai sekian bulan ke depan.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Pending Approval'), ('approved', 'Approved'), ('committed', 'Committed'), ('partial', 'Partially Committed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('commit_error', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_setups', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Site yang disetup. Satu dokumen = satu site.', on_delete=django.db.models.deletion.PROTECT, related_name='roster_setups', to='administration.location')),
                ('section', models.ForeignKey(blank=True, help_text='Penyaring opsional. Kosong = seluruh site.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_setups', to='administration.section')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_roster_setup_request',
                'ordering': ['-as_of_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='rostersetupline',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hr.rostersetuprequest'),
        ),
        migrations.AddIndex(
            model_name='rosterplanversion',
            index=models.Index(fields=['plan', 'version_no'], name='idx_roster_version_plan'),
        ),
        migrations.AddConstraint(
            model_name='rosterplanversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('plan', 'version_no'), name='uniq_active_roster_plan_version'),
        ),
        migrations.AddIndex(
            model_name='rostersetuprequest',
            index=models.Index(fields=['status'], name='idx_roster_setup_status'),
        ),
        migrations.AddIndex(
            model_name='rostersetuprequest',
            index=models.Index(fields=['location', 'as_of_date'], name='idx_roster_setup_scope'),
        ),
        migrations.AddConstraint(
            model_name='rostersetuprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('document_number', ''), _negated=True)), fields=('document_number',), name='uniq_active_hr_roster_setup_number'),
        ),
        migrations.AddIndex(
            model_name='rostersetupline',
            index=models.Index(fields=['employee'], name='idx_roster_setup_line_emp'),
        ),
        migrations.AddConstraint(
            model_name='rostersetupline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('request', 'employee'), name='uniq_active_roster_setup_line'),
        ),
    ]
