# Generated by Django 6.0.6 on 2026-08-12 06:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0034_backfill_roster_segments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('expired', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('carried_excess_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_credit_balance', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_rotation_credit_balance',
                'ordering': ['employee__employee_number'],
                'indexes': [models.Index(fields=['balance'], name='idx_rotation_credit_balance')],
            },
        ),
        migrations.CreateModel(
            name='RotationCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('earned', 'Earned'), ('used', 'Used'), ('adjustment_plus', 'Adjustment (+)'), ('adjustment_minus', 'Adjustment (−)'), ('expired', 'Expired'), ('reversal', 'Reversal')], max_length=20)),
                ('days', models.DecimalField(decimal_places=2, help_text='Selalu positif. Arahnya ditentukan Entry Type.', max_digits=6)),
                ('transaction_date', models.DateField(help_text='Kapan transaksi ini dicatat.')),
                ('effective_date', models.DateField(help_text='Kapan berlakunya. Boleh mundur — saldo awal dari sistem lama berlaku sejak tanggal go-live, bukan sejak diketik.')),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', max_length=50)),
                ('remainder_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sisa hari kerja yang belum genap jadi satu kredit.', max_digits=6)),
                ('conversion_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_credits', to='hr.employee')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_credits', to='hr.siterotation')),
                ('reverses', models.ForeignKey(blank=True, help_text='Transaksi yang dibatalkan baris ini.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='hr.rotationcredittransaction')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_credits', to='hr.rotationperiod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_rotation_credit_transaction',
                'ordering': ['-effective_date', '-id'],
                'indexes': [models.Index(fields=['employee', 'effective_date'], name='idx_rotation_credit_emp_date'), models.Index(fields=['entry_type'], name='idx_rotation_credit_type'), models.Index(fields=['source_type', 'source_id'], name='idx_rotation_credit_source')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('reverses__isnull', False)), fields=('reverses',), name='uniq_active_rotation_credit_reversal')],
            },
        ),
    ]
