# Generated by Django 6.0.6 on 2026-08-12 06:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_roster_policy_cycle_pattern'),
        ('hr', '0035_rotation_credit_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('adjustment_kind', models.CharField(choices=[('work_extension', 'Work Extension'), ('early_return', 'Early Return'), ('deferred_leave', 'Deferred Leave (KTT approved)'), ('late_return', 'Late Return (employee fault)'), ('loyalty', 'Deferred Leave (no approval)'), ('no_impact', 'No Impact (beyond employee control)'), ('schedule_shift', 'Schedule Shift'), ('credit_use', 'Use Rotation Credit')], max_length=30)),
                ('effective_date', models.DateField(help_text='Perubahan berlaku dari tanggal ini ke depan. Jadwal sebelumnya tidak disentuh.')),
                ('days', models.PositiveSmallIntegerField(default=0, help_text='Selalu positif. Arahnya ditentukan jenis penyesuaian.')),
                ('new_cycle_start', models.DateField(blank=True, help_text='Untuk kasus jangkar digeser, bukan blok diperpanjang. Dikosongkan = jangkar dihitung dari jadwal yang bertahan.', null=True)),
                ('credit_impact', models.CharField(choices=[('none', 'No Credit Impact'), ('earn', 'Earn Credit'), ('use', 'Use Credit')], default='none', max_length=10)),
                ('credit_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, default='', help_text='Nomor TR, nomor tiket, atau nomor memo.', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Pending Approval'), ('approved', 'Approved'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_error', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_adjustments', to='administration.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_adjustments', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_adjustments', to='hr.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_adjustments', to='administration.location')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='hr.siterotation')),
                ('resulting_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='hr.rosterplanversion')),
                ('segment', models.ForeignKey(blank=True, help_text='Segmen sasaran. Dikosongkan = ditentukan dari Effective Date.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='hr.rotationperiod')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_roster_adjustment',
                'ordering': ['-effective_date', '-id'],
                'indexes': [models.Index(fields=['plan', 'effective_date'], name='idx_roster_adj_plan_date'), models.Index(fields=['status'], name='idx_roster_adj_status'), models.Index(fields=['employee'], name='idx_roster_adj_employee')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('document_number', ''), _negated=True)), fields=('document_number',), name='uniq_active_hr_roster_adjustment_number')],
            },
        ),
    ]
