# Generated by Django 6.0.6 on 2026-08-12 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_roster_policy_cycle_pattern'),
        ('hr', '0036_roster_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rostersetuprequest',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Penyaring opsional. Kosong = seluruh site.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_setups', to='administration.department'),
        ),
        migrations.AlterField(
            model_name='rostersetuprequest',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Penyaring opsional, di bawah Department. Kosong = seluruh department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_setups', to='administration.section'),
        ),
    ]
