# Generated by Django 6.0.6 on 2026-08-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0037_rostersetuprequest_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='leave_required_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hari cuti yang seharusnya diambil untuk hari ini menurut Attendance Policy. Nol = tidak ada.', max_digits=4),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='leave_required_reason',
            field=models.CharField(blank=True, choices=[('late', 'Terlambat'), ('early_leave', 'Pulang cepat'), ('both', 'Terlambat & pulang cepat')], default='', help_text='Sebabnya, supaya baris yang ditandai bisa dijelaskan tanpa membandingkan jam tap dengan jadwalnya satu per satu.', max_length=20),
        ),
    ]
