# Generated by Django 6.0.6 on 2026-08-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0038_employeeattendance_leave_required_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereminderpolicy',
            name='email_milestones',
            field=models.CharField(blank=True, default='30,14,7,1', help_text='Sisa hari saat email dikirim, dipisah koma. Bel diperbarui tiap hari sebagai hitung mundur; email tidak boleh begitu — tiga puluh salinan surat yang sama membuat orang berhenti membaca yang ke-31. Dikosongkan = tidak ada email pengingat, hanya bel.', max_length=100),
        ),
    ]
