# Generated by Django 6.0.6 on 2026-08-15 15:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0039_employeereminderpolicy_email_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='carried_over_expires_at',
            field=models.DateField(blank=True, help_text='Tanggal sisa bawaan hangus. Dikosongkan = tidak hangus.', null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carried_over_forfeited',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Sisa bawaan yang sudah hangus karena lewat tanggalnya.', max_digits=6),
        ),
    ]
