# Generated by Django 6.0.6 on 2026-08-16 04:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_leavepolicy_carry_over_reminder_days'),
        ('hr', '0040_leavebalance_carried_over_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='opening_balance',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Saldo awal saat ERP mulai dipakai. Terisi otomatis dari dokumen Leave Opening Balance.', max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='opening_expires_at',
            field=models.DateField(blank=True, help_text='Tanggal saldo awal hangus. Dikosongkan = tidak hangus.', null=True),
        ),
        migrations.CreateModel(
            name='LeaveOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('opening_date', models.DateField(help_text='Tanggal saldo ini berlaku, lazimnya tanggal ERP mulai dipakai.')),
                ('year', models.PositiveSmallIntegerField(help_text='Tahun kartu saldo yang menerima angka ini.')),
                ('days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Sisa saldo dari sistem lama, dalam hari.', max_digits=6)),
                ('expires_at', models.DateField(blank=True, help_text='Tanggal saldo awal hangus. Dikosongkan = tidak hangus.', null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import')], default='manual', max_length=20)),
                ('remark', models.TextField(blank=True, default='', help_text="Dari mana angkanya, mis. 'Saldo per 16 Agustus 2026 dari sistem HR lama'.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_opening_balances', to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_opening_balances', to='administration.leavetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_leave_opening_balance',
                'ordering': ['-opening_date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'year'], name='idx_leave_opening_emp_year')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee', 'leave_type'), name='uniq_active_hr_leave_opening_balance')],
            },
        ),
    ]
