# Generated by Django 6.0.6 on 2026-08-16 05:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0041_leavebalance_opening_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='advance_used',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Pemakaian yang melebihi seluruh kantong.', max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carried_over_used',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Bagian pemakaian yang menggerus sisa tahun lalu.', max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='opening_forfeited',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Saldo awal yang sudah hangus karena lewat tanggalnya.', max_digits=6),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='opening_used',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Bagian pemakaian yang menggerus saldo awal.', max_digits=6),
        ),
    ]
