# Generated by Django 6.0.6 on 2026-08-16 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0042_leavebalance_advance_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_obligations', to='hr.employeeleave'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='leave_required_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Angka yang ditetapkan atasan/HR, menggantikan hitungan aturan. Dikosongkan = ikut aturan.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='leave_required_waived',
            field=models.BooleanField(default=False, help_text='Dibebaskan — tidak perlu mengajukan cuti untuk hari ini.'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='leave_required_waiver_reason',
            field=models.TextField(blank=True, default='', help_text='Wajib diisi saat membebaskan. Pembebasan tanpa alasan tertulis membuat aturan ini kehilangan wibawanya dalam tiga bulan.'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='review_decision',
            field=models.CharField(blank=True, choices=[('valid', 'Pengecualian sah'), ('require_leave', 'Harus mengajukan cuti')], default='', help_text='Kosong = belum ditinjau atasan.', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
