# Generated by Django 6.0.6 on 2026-08-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0035_district_village_city_aid_province_aid_and_more'),
        ('hr', '0044_externalvisitor_visitorrequest_visitorpass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Alamat detail: nama jalan, nomor, RT/RW. Wilayah administratifnya diisi di field Province sampai Kelurahan/Desa.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='administration.city', verbose_name='Kabupaten/Kota'),
        ),
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='administration.district', verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='administration.province'),
        ),
        migrations.AddField(
            model_name='employee',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='administration.village', verbose_name='Kelurahan/Desa'),
        ),
    ]
