# Generated by Django 6.0.6 on 2026-08-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0045_employee_address_employee_city_employee_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveopeningbalance',
            name='replaces_entitlement',
            field=models.BooleanField(default=False, help_text='Nyalakan kalau angka ini sudah termasuk jatah tahun berjalan. Jatah tahun itu jadi nol, dan yang berlaku angka di dokumen ini. Tahun berikutnya kembali normal.'),
        ),
    ]
