# Generated by Django 6.0.6 on 2026-08-19 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0035_district_village_city_aid_province_aid_and_more'),
        ('hr', '0046_leaveopeningbalance_replaces_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveopeningbalance',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveopeningbalance',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_leave_opening_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveopeningbalance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', help_text='Draft belum memengaruhi kartu saldo. Posted sudah.', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveGoLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('go_live_date', models.DateField(help_text='Hari pertama cuti dikelola di sistem ini. Saldo per hari sebelumnya masuk lewat Leave Opening Balance.')),
                ('is_active', models.BooleanField(default=True, help_text='Matikan untuk mengembalikan perhitungan jatah ke aturan biasa, mis. kalau tanggalnya ternyata salah.')),
                ('notes', models.TextField(blank=True, default='', help_text='Dari sistem apa datanya dipindah, dan siapa yang menyerahkan angkanya.')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_go_live', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_leave_go_live',
                'ordering': ['-go_live_date', 'company'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company',), name='uniq_active_hr_leave_go_live_company')],
            },
        ),
    ]
