# Generated by Django 6.0.6 on 2026-08-24 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0051_travel_request_purpose_leave_issued'),
        ('imports', '0006_alter_importprofile_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedevice',
            name='import_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_devices', to='imports.importprofile'),
        ),
        migrations.CreateModel(
            name='AttendanceDeviceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('external_employee_id', models.CharField(db_index=True, help_text='Nomor pegawai menurut mesin (No.ID / PIN / enroll number). Bukan Employee Number ERP.', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='hr.attendancedevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_mappings', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_attendance_device_employee',
                'ordering': ['device_id', 'external_employee_id'],
                'indexes': [models.Index(fields=['device', 'is_active'], name='idx_hr_att_dev_emp_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('device', 'external_employee_id'), name='uq_hr_att_device_employee_external')],
            },
        ),
    ]
