# Generated by Django 6.0.6 on 2026-08-26 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0037_employeegroup_feature_applicability'),
        ('hr', '0052_attendancedevice_import_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('layer', models.CharField(choices=[('baseline', 'Roster Baseline'), ('override', 'Adjustment')], db_index=True, default='baseline', help_text='Baseline = rencana shift blok kerja. Adjustment = penyesuaian yang menang atas baseline pada rentangnya.', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', help_text='Kenapa shift-nya berbeda. Wajib untuk Adjustment.', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hr.employee')),
                ('shift', models.ForeignKey(help_text='Jam kerjanya milik master Shift — mengubah jam di sana mengubah jendela terjadwal tanpa perubahan kode.', on_delete=django.db.models.deletion.PROTECT, related_name='employee_shift_assignments', to='administration.shift')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee_shift_assignment',
                'ordering': ['employee', 'start_date', 'layer'],
                'indexes': [models.Index(fields=['employee', 'start_date', 'end_date'], name='idx_shift_assignment_emp_range')],
            },
        ),
    ]
