# Generated by Django 6.0.6 on 2026-09-02 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0039_rosterpolicy_min_rest_hours'),
        ('hr', '0053_employeeshiftassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftassignment',
            name='kind',
            field=models.CharField(choices=[('work', 'Working Shift'), ('rest', 'Recovery / Rest')], db_index=True, default='work', help_text='Working Shift = baris ini menetapkan shift. Recovery / Rest = baris ini justru menyatakan tidak ada shift, dan tanggalnya tidak menerbitkan kewajiban presensi.', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeshiftassignment',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Jam kerjanya milik master Shift — mengubah jam di sana mengubah jendela terjadwal tanpa perubahan kode. Dikosongkan hanya untuk baris Recovery / Rest.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_shift_assignments', to='administration.shift'),
        ),
    ]
