# Generated by Django 6.0.6 on 2026-09-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0054_employeeshiftassignment_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollassignment',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
