# Generated by Django 6.0.6 on 2026-09-04 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0055_payrollassignment_daily_rate'),
        ('payroll', '0008_payrollrunemployee_daily_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollassignment',
            name='payroll_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_payroll_assignments', to='payroll.payrollpolicy'),
        ),
    ]
