# Generated by Django 6.0.6 on 2026-09-07 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0041_backfill_calendar_scope'),
        ('hr', '0056_payrollassignment_payroll_policy'),
        ('uploads', '0003_alter_uploadedfile_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='excused_early_leave_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Bagian dari `early_leave_minutes` yang tertutup izin yang disetujui.'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='excused_late_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Bagian dari `late_minutes` yang tertutup izin yang disetujui. Sisanya keterlambatan tanpa izin.'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='is_excused_absence',
            field=models.BooleanField(db_index=True, default=False, help_text='Tidak masuk dengan izin yang disetujui — bukan mangkir. Perlakuan payroll-nya tetap mengikuti Payroll Permission Rule, bukan kolom ini.'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='permission_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Menit izin keluar sementara yang disetujui pada hari ini.'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='permission_state',
            field=models.CharField(blank=True, choices=[('pending', 'Izin menunggu persetujuan'), ('excused', 'Tertutup izin'), ('partial', 'Sebagian tertutup izin'), ('unauthorized', 'Tanpa izin')], db_index=True, default='', help_text='Kosong = tidak ada pengecualian yang perlu dijelaskan.', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendancePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('permission_type', models.CharField(choices=[('late_arrival', 'Late Arrival'), ('early_leave', 'Early Leave'), ('temporary_out', 'Temporary Out'), ('full_day', 'Full Day Permission')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, help_text='Early Leave: boleh pulang mulai jam ini. Temporary Out: jam mulai izin. Late Arrival & Full Day: dikosongkan.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Late Arrival: boleh datang paling lambat jam ini. Temporary Out: jam kembali. Early Leave & Full Day: dikosongkan.', null=True)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('allow_outside_shift', models.BooleanField(default=False, help_text='Override HR: terima izin yang jam-nya di luar jendela shift pegawai. Wajib disertai alasan.')),
                ('outside_shift_reason', models.TextField(blank=True, default='', help_text='Wajib diisi saat override dinyalakan. Override tanpa alasan tertulis tidak bisa dijelaskan saat diaudit.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_permissions', to='administration.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_permissions', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_permissions', to='hr.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_permissions', to='administration.location')),
                ('supporting_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uploads.uploadedfile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Permission',
                'verbose_name_plural': 'Attendance Permissions',
                'db_table': 'hr_attendance_permission',
                'ordering': ['-date', 'employee_id', '-id'],
                'indexes': [models.Index(fields=['employee', 'date'], name='idx_att_perm_employee_date'), models.Index(fields=['company', 'date'], name='idx_att_perm_company_date'), models.Index(fields=['status', 'date'], name='idx_att_perm_status_date')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('document_number', ''), _negated=True)), fields=('document_number',), name='uniq_active_hr_attendance_permission_number')],
            },
        ),
    ]
