# Generated by Django 6.0.6 on 2026-09-15 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0057_employeeattendance_excused_early_leave_minutes_and_more'),
        ('uploads', '0003_alter_uploadedfile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar_file',
            field=models.ForeignKey(blank=True, help_text='Foto pegawai. Diunggah lewat kerangka unggahan dengan kategori Avatar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploads.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Kolom foto lama. Hanya dibaca untuk kompatibilitas; foto baru masuk lewat Avatar File.', null=True, upload_to='employees/avatars/'),
        ),
    ]
