# Generated by Django 6.0.6 on 2026-09-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0058_employee_avatar_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeleave',
            options={'ordering': ['-start_date', 'employee'], 'permissions': [('record_employeeleave', 'Can record leave without approval')]},
        ),
    ]
