# Generated by Django 6.0.6 on 2026-09-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0059_employeeleave_record_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancepermission',
            options={'ordering': ['-date', 'employee_id', '-id'], 'permissions': [('override_attendancepermission', 'Can allow attendance permission outside shift')], 'verbose_name': 'Attendance Permission', 'verbose_name_plural': 'Attendance Permissions'},
        ),
    ]
