# Generated by Django 6.0.6 on 2026-09-30 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0061_business_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='business_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_days', to='hr.businesstrip'),
        ),
    ]
