# Generated by Django 6.0.6 on 2026-10-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0062_employeeattendance_business_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLogVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('review_required', 'Review Required')], db_index=True, default='pending', max_length=20)),
                ('reason_code', models.CharField(blank=True, choices=[('punch_too_soon', 'Punch too soon after the previous one'), ('duplicate_check_in', 'Already checked in'), ('check_out_without_check_in', 'Check out without check in'), ('duplicate_check_out', 'Already checked out'), ('location_not_verified', 'Location not verified'), ('location_unavailable', 'Location unavailable'), ('location_low_accuracy', 'Location accuracy too low'), ('geofence_not_verified', 'Geofence not verified'), ('outside_geofence', 'Outside geofence'), ('liveness_not_verified', 'Liveness not verified'), ('liveness_failed', 'Liveness failed'), ('face_not_verified', 'Face not verified'), ('face_mismatch', 'Face mismatch'), ('validator_error', 'Validator error'), ('payroll_period_locked', 'Payroll period locked'), ('day_closed_absent', 'Day already closed as absent'), ('on_leave', 'On leave')], default='', max_length=40)),
                ('reason_detail', models.TextField(blank=True, default='')),
                ('work_date', models.DateField(blank=True, null=True)),
                ('face_result', models.CharField(choices=[('not_required', 'Not Required'), ('not_configured', 'Not Configured'), ('not_run', 'Not Run'), ('pass', 'Pass'), ('fail', 'Fail'), ('error', 'Error')], default='not_run', max_length=20)),
                ('face_score', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('face_threshold', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('face_provider', models.CharField(blank=True, default='', max_length=100)),
                ('face_model_version', models.CharField(blank=True, default='', max_length=100)),
                ('liveness_result', models.CharField(choices=[('not_required', 'Not Required'), ('not_configured', 'Not Configured'), ('not_run', 'Not Run'), ('pass', 'Pass'), ('fail', 'Fail'), ('error', 'Error')], default='not_run', max_length=20)),
                ('liveness_score', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('liveness_threshold', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('liveness_provider', models.CharField(blank=True, default='', max_length=100)),
                ('liveness_model_version', models.CharField(blank=True, default='', max_length=100)),
                ('location_result', models.CharField(choices=[('not_required', 'Not Required'), ('not_configured', 'Not Configured'), ('not_run', 'Not Run'), ('pass', 'Pass'), ('low_accuracy', 'Low Accuracy'), ('unavailable', 'Unavailable'), ('error', 'Error')], default='not_run', max_length=20)),
                ('gps_accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('geofence_result', models.CharField(choices=[('not_required', 'Not Required'), ('not_configured', 'Not Configured'), ('not_run', 'Not Run'), ('inside', 'Inside'), ('outside', 'Outside'), ('error', 'Error')], default='not_run', max_length=20)),
                ('distance_from_geofence_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('geofence_radius_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='hr.attendancelog')),
            ],
            options={
                'db_table': 'hr_attendance_log_verification',
                'ordering': ['-id'],
            },
        ),
    ]
