# Generated by Django 6.0.6 on 2026-10-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0043_employeegroup_business_trip_applicable'),
        ('hr', '0063_attendance_log_verification'),
        ('imports', '0006_alter_importprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedevice',
            name='agent_key_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='agent_key_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='agent_key_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='agent_key_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='attendancedevice',
            constraint=models.UniqueConstraint(condition=models.Q(('agent_key_id', ''), _negated=True), fields=('agent_key_id',), name='uq_hr_att_device_agent_key_id'),
        ),
    ]
