# Generated by Django 6.0.6 on 2026-10-04 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0064_attendance_device_agent_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelogverification',
            name='face_result',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('not_configured', 'Not Configured'), ('not_run', 'Not Run'), ('pass', 'Pass'), ('fail', 'Fail'), ('error', 'Error'), ('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces'), ('not_enrolled', 'Not Enrolled')], default='not_run', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancelogverification',
            name='liveness_result',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('not_configured', 'Not Configured'), ('not_run', 'Not Run'), ('pass', 'Pass'), ('fail', 'Fail'), ('error', 'Error'), ('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces'), ('not_enrolled', 'Not Enrolled')], default='not_run', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancelogverification',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('punch_too_soon', 'Punch too soon after the previous one'), ('duplicate_check_in', 'Already checked in'), ('check_out_without_check_in', 'Check out without check in'), ('duplicate_check_out', 'Already checked out'), ('location_not_verified', 'Location not verified'), ('location_unavailable', 'Location unavailable'), ('location_low_accuracy', 'Location accuracy too low'), ('geofence_not_verified', 'Geofence not verified'), ('outside_geofence', 'Outside geofence'), ('liveness_not_verified', 'Liveness not verified'), ('liveness_failed', 'Liveness failed'), ('face_not_verified', 'Face not verified'), ('face_mismatch', 'Face mismatch'), ('validator_error', 'Validator error'), ('no_face', 'No face detected'), ('multiple_faces', 'Multiple faces detected'), ('not_enrolled', 'Not enrolled for face verification'), ('selfie_replayed', 'Selfie already used'), ('payroll_period_locked', 'Payroll period locked'), ('day_closed_absent', 'Day already closed as absent'), ('on_leave', 'On leave')], default='', max_length=40),
        ),
        migrations.CreateModel(
            name='EmployeeBiometricEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('enrollment_source', models.CharField(choices=[('hr_assisted', 'HR Assisted'), ('self_service', 'Self Service')], max_length=20)),
                ('enrolled_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_enrollments', to='hr.employee')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee_biometric_enrollment',
                'ordering': ['employee_id', 'provider', '-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('employee', 'provider'), name='uq_hr_bio_enroll_one_active'), models.UniqueConstraint(fields=('employee', 'provider', 'version'), name='uq_hr_bio_enroll_version'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('status', 'revoked')), _connector='OR'), name='ck_hr_bio_enroll_revoked_at')],
            },
        ),
    ]
