# Generated by Django 6.0.6 on 2026-10-04 10:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0043_employeegroup_business_trip_applicable'),
        ('hr', '0065_employee_biometric_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelogverification',
            name='geofence_result',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('not_configured', 'Not Configured'), ('not_run', 'Not Run'), ('inside', 'Inside'), ('outside', 'Outside'), ('error', 'Error'), ('no_geofence', 'No Geofence For Work Location'), ('no_work_location', 'No Work Location')], default='not_run', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancelogverification',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('punch_too_soon', 'Punch too soon after the previous one'), ('duplicate_check_in', 'Already checked in'), ('check_out_without_check_in', 'Check out without check in'), ('duplicate_check_out', 'Already checked out'), ('location_not_verified', 'Location not verified'), ('location_unavailable', 'Location unavailable'), ('location_low_accuracy', 'Location accuracy too low'), ('geofence_not_verified', 'Geofence not verified'), ('outside_geofence', 'Outside geofence'), ('liveness_not_verified', 'Liveness not verified'), ('liveness_failed', 'Liveness failed'), ('face_not_verified', 'Face not verified'), ('face_mismatch', 'Face mismatch'), ('validator_error', 'Validator error'), ('geofence_not_configured', 'Work location has no geofence'), ('work_location_unavailable', 'Work location unavailable'), ('trial_not_recorded', 'Trial punch, attendance not recorded'), ('no_face', 'No face detected'), ('multiple_faces', 'Multiple faces detected'), ('not_enrolled', 'Not enrolled for face verification'), ('selfie_replayed', 'Selfie already used'), ('payroll_period_locked', 'Payroll period locked'), ('day_closed_absent', 'Day already closed as absent'), ('on_leave', 'On leave')], default='', max_length=40),
        ),
        migrations.CreateModel(
            name='AttendanceGeofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('radius_m', models.PositiveIntegerField(help_text='Radius area kerja dalam meter, dari titik pusat.', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_geofences', to='administration.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_attendance_geofence',
                'ordering': ['location_id', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('location',), name='uq_hr_att_geofence_active_location'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='ck_hr_att_geofence_latitude'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='ck_hr_att_geofence_longitude'), models.CheckConstraint(condition=models.Q(('radius_m__gt', 0)), name='ck_hr_att_geofence_radius')],
            },
        ),
    ]
