# Generated by Django 6.0.6 on 2026-07-27 06:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_shift_workschedule_workscheduleday_and_more'),
        ('hr', '0002_employmentassignment_organizationassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='JobGrade',
        ),
        migrations.AlterModelTable(
            name='jobgrade',
            table='master_job_grade',
        ),
    ]
