# Generated by Django 6.0.6 on 2026-07-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_certificationbody'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificationBody',
        ),
    ]
