# Generated by Django 6.0.6 on 2026-08-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_delete_certificationbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='category',
            field=models.CharField(choices=[('IDENTITY', 'Identity'), ('FAMILY', 'Family'), ('TAX', 'Tax'), ('EDUCATION', 'Education'), ('EMPLOYMENT', 'Employment'), ('LICENSE', 'License'), ('HEALTH', 'Health'), ('FINANCE', 'Finance'), ('IMMIGRATION', 'Immigration'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_expirable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='requires_issue_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='requires_issuing_authority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='requires_number',
            field=models.BooleanField(default=False),
        ),
    ]
