# Generated by Django 6.0.6 on 2026-08-07 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_documenttype_allow_multiple_documenttype_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestatus',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodtype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='branchtype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidatestatus',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='competency',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='competencycategory',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='competencylevel',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='dashboardtemplate',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='degree',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencyrelationship',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeegroup',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employmenttype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exitclearancestatus',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familyrelationship',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gender',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewtype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobfamily',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobgrade',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblevel',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kpicategory',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kpiperiod',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kpiweighttype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='languageproficiency',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leavereason',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='overtimetype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='performancecycle',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='performancerating',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='performancetemplate',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='probationtype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recruitmentsource',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rejectionreason',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='religion',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shiftgroup',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitetype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studyfield',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='terminationreason',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingcategory',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingprovider',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='attendancestatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_attendancestatus_code'),
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_bank_code'),
        ),
        migrations.AddConstraint(
            model_name='bloodtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_bloodtype_code'),
        ),
        migrations.AddConstraint(
            model_name='branchtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_branchtype_code'),
        ),
        migrations.AddConstraint(
            model_name='candidatestatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_candidatestatus_code'),
        ),
        migrations.AddConstraint(
            model_name='certificatetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_certificatetype_code'),
        ),
        migrations.AddConstraint(
            model_name='companytype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_companytype_code'),
        ),
        migrations.AddConstraint(
            model_name='competency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_competency_code'),
        ),
        migrations.AddConstraint(
            model_name='competencycategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_competencycategory_code'),
        ),
        migrations.AddConstraint(
            model_name='competencylevel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_competencylevel_code'),
        ),
        migrations.AddConstraint(
            model_name='contracttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_contracttype_code'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_country_code'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_currency_code'),
        ),
        migrations.AddConstraint(
            model_name='dashboardtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_dashboardtemplate_code'),
        ),
        migrations.AddConstraint(
            model_name='dashboardwidget',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_dashboardwidget_code'),
        ),
        migrations.AddConstraint(
            model_name='degree',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_degree_code'),
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_documenttype_code'),
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_education_code'),
        ),
        migrations.AddConstraint(
            model_name='emergencyrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_emergencyrelationship_code'),
        ),
        migrations.AddConstraint(
            model_name='employeegroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_employeegroup_code'),
        ),
        migrations.AddConstraint(
            model_name='employmentstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_employmentstatus_code'),
        ),
        migrations.AddConstraint(
            model_name='employmenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_employmenttype_code'),
        ),
        migrations.AddConstraint(
            model_name='exitclearancestatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_exitclearancestatus_code'),
        ),
        migrations.AddConstraint(
            model_name='familyrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_familyrelationship_code'),
        ),
        migrations.AddConstraint(
            model_name='gender',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_gender_code'),
        ),
        migrations.AddConstraint(
            model_name='interviewtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_interviewtype_code'),
        ),
        migrations.AddConstraint(
            model_name='jobcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_jobcategory_code'),
        ),
        migrations.AddConstraint(
            model_name='jobfamily',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_jobfamily_code'),
        ),
        migrations.AddConstraint(
            model_name='jobgrade',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_jobgrade_code'),
        ),
        migrations.AddConstraint(
            model_name='joblevel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_joblevel_code'),
        ),
        migrations.AddConstraint(
            model_name='kpicategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_kpicategory_code'),
        ),
        migrations.AddConstraint(
            model_name='kpiperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_kpiperiod_code'),
        ),
        migrations.AddConstraint(
            model_name='kpiweighttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_kpiweighttype_code'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_language_code'),
        ),
        migrations.AddConstraint(
            model_name='languageproficiency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_languageproficiency_code'),
        ),
        migrations.AddConstraint(
            model_name='leavereason',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_leavereason_code'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_leavetype_code'),
        ),
        migrations.AddConstraint(
            model_name='licensetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_licensetype_code'),
        ),
        migrations.AddConstraint(
            model_name='maritalstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_maritalstatus_code'),
        ),
        migrations.AddConstraint(
            model_name='nationality',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_nationality_code'),
        ),
        migrations.AddConstraint(
            model_name='overtimetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_overtimetype_code'),
        ),
        migrations.AddConstraint(
            model_name='performancecycle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_performancecycle_code'),
        ),
        migrations.AddConstraint(
            model_name='performancerating',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_performancerating_code'),
        ),
        migrations.AddConstraint(
            model_name='performancetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_performancetemplate_code'),
        ),
        migrations.AddConstraint(
            model_name='probationtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_probationtype_code'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentsource',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_recruitmentsource_code'),
        ),
        migrations.AddConstraint(
            model_name='rejectionreason',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_rejectionreason_code'),
        ),
        migrations.AddConstraint(
            model_name='religion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_religion_code'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_shift_code'),
        ),
        migrations.AddConstraint(
            model_name='shiftgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_shiftgroup_code'),
        ),
        migrations.AddConstraint(
            model_name='sitetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_sitetype_code'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_skill_code'),
        ),
        migrations.AddConstraint(
            model_name='skilllevel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_skilllevel_code'),
        ),
        migrations.AddConstraint(
            model_name='studyfield',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_studyfield_code'),
        ),
        migrations.AddConstraint(
            model_name='terminationreason',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_terminationreason_code'),
        ),
        migrations.AddConstraint(
            model_name='trainingcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_trainingcategory_code'),
        ),
        migrations.AddConstraint(
            model_name='trainingprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_trainingprovider_code'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_workschedule_code'),
        ),
    ]
