# Generated by Django 6.0.6 on 2026-08-08 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_rename_site_to_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holiday',
            name='uniq_core_holiday_company_site_date',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='uniq_core_site_company_code',
        ),
        migrations.RemoveConstraint(
            model_name='locationtype',
            name='uniq_active_administration_sitetype_code',
        ),
        migrations.RemoveIndex(
            model_name='audittrail',
            name='master_audi_site_id_4ef991_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowdelegation',
            name='master_work_company_db50e4_idx',
        ),
        migrations.AlterField(
            model_name='location',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='administration.branch'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='administration.city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='administration.company'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='administration.country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='administration.locationtype'),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='administration.province'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['location'], name='master_audi_locatio_9f8c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdelegation',
            index=models.Index(fields=['company', 'location'], name='master_work_company_018af4_idx'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('company', 'location', 'date'), name='uniq_core_holiday_company_location_date'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_core_location_company_code'),
        ),
        migrations.AddConstraint(
            model_name='locationtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_administration_locationtype_code'),
        ),
    ]
