# Generated by Django 6.0.6 on 2026-08-09 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_rotationpurpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('entitlement_days', models.DecimalField(decimal_places=2, default=12, help_text='Jatah penuh untuk satu periode, mis. 12 hari setahun.', max_digits=6)),
                ('accrual', models.CharField(choices=[('upfront', 'Sekaligus di Awal'), ('monthly', 'Terkumpul Bulanan')], default='upfront', max_length=20)),
                ('period_basis', models.CharField(choices=[('calendar', 'Tahun Kalender'), ('join_date', 'Ulang Tahun Masa Kerja')], default='calendar', max_length=20)),
                ('eligible_after_months', models.PositiveSmallIntegerField(default=12, help_text='Masa tunggu sejak Join Date sebelum jatah pertama terbit. 12 = cuti tahunan baru ada setelah setahun bekerja (UU Ketenagakerjaan). 0 = berlaku sejak hari pertama.')),
                ('prorate_first_period', models.BooleanField(default=True, help_text='Periode pertama dihitung sebanding sisa bulannya, bukan penuh. Pegawai yang mulai berhak di bulan Agustus dapat 5/12 jatah untuk tahun itu.')),
                ('allow_carry_over', models.BooleanField(default=False)),
                ('carry_over_max_days', models.DecimalField(blank=True, decimal_places=2, help_text='Batas sisa yang boleh dibawa ke periode berikutnya. Dikosongkan = tanpa batas.', max_digits=6, null=True)),
                ('carry_over_expiry_months', models.PositiveSmallIntegerField(blank=True, help_text='Sisa bawaan hangus setelah sekian bulan periode baru berjalan. Dikosongkan = tidak hangus.', null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua company yang tidak punya aturannya sendiri.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='administration.employeegroup')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='administration.employmenttype')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='administration.leavetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_leave_policy',
                'ordering': ['leave_type', 'company', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'code'), name='uniq_active_administration_leavepolicy_code'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'leave_type', 'employee_group', 'employment_type'), name='uniq_active_leavepolicy_target')],
            },
        ),
    ]
