# Generated by Django 6.0.6 on 2026-08-09 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_leavepolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('default_travel_days', models.PositiveSmallIntegerField(default=2, help_text='Hari perjalanan sekali jalan untuk POH yang belum didaftarkan di tabel di bawah.')),
                ('conversion_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Perbandingan hari kerja : hari off. Dikosongkan = dihitung sendiri dari pola roster pegawai (56:14 = 4). Diisi hanya kalau perusahaan memakai angka yang berbeda dari polanya.', max_digits=5, null=True)),
                ('request_lead_days', models.PositiveSmallIntegerField(default=7, help_text='Travel Request diajukan minimal sekian hari sebelum tanggal berangkat. 0 = tanpa tenggat.')),
                ('notify_lead_days', models.PositiveSmallIntegerField(default=7, help_text='Sistem mengingatkan sekian hari sebelum tanggal berangkat kalau Travel Request-nya belum dibuat.')),
                ('company', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua company yang tidak punya aturannya sendiri.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_policies', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Site yang diatur. Dikosongkan = berlaku untuk semua site di company itu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_policies', to='administration.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('urgent_purposes', models.ManyToManyField(blank=True, help_text='Travel Purpose yang boleh diajukan mendadak, menembus tenggat di atas.', related_name='roster_policies', to='administration.rotationpurpose')),
            ],
            options={
                'db_table': 'master_roster_policy',
                'ordering': ['company', 'location', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RosterTravelDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('travel_days', models.PositiveSmallIntegerField(default=2, help_text='Hari perjalanan sekali jalan, bukan pulang-pergi.')),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('point_of_hire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_travel_days', to='administration.city')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_days', to='administration.rosterpolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_roster_travel_day',
                'ordering': ['policy', 'point_of_hire'],
            },
        ),
        migrations.AddConstraint(
            model_name='rosterpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'code'), name='uniq_active_administration_rosterpolicy_code'),
        ),
        migrations.AddConstraint(
            model_name='rosterpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'location'), name='uniq_active_rosterpolicy_target'),
        ),
        migrations.AddConstraint(
            model_name='rostertravelday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('policy', 'point_of_hire'), name='uniq_active_rostertravelday_poh'),
        ),
    ]
