# Generated by Django 6.0.6 on 2026-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_rosterpolicy_rostertravelday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='accrual',
            field=models.CharField(choices=[('upfront', 'Upfront'), ('monthly', 'Monthly Accrual')], default='upfront', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='period_basis',
            field=models.CharField(choices=[('calendar', 'Calendar Year'), ('join_date', 'Employment Anniversary')], default='calendar', max_length=20),
        ),
    ]
