# Generated by Django 6.0.6 on 2026-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_alter_leavepolicy_accrual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterpolicy',
            name='default_travel_days',
            field=models.PositiveSmallIntegerField(default=2, help_text='Total hari perjalanan pulang-pergi untuk POH yang belum didaftarkan di tabel di bawah.'),
        ),
        migrations.AlterField(
            model_name='rostertravelday',
            name='travel_days',
            field=models.PositiveSmallIntegerField(default=2, help_text='Total pulang-pergi. 2 = sehari keluar, sehari kembali.'),
        ),
    ]
