# Generated by Django 6.0.6 on 2026-08-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_facilitytype_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttype',
            name='requires_contract',
            field=models.BooleanField(default=False, help_text='Jenis ini terikat masa kontrak — Contract Type, Contract Start, dan Contract End berlaku untuknya. Kosongkan untuk pegawai tetap.'),
        ),
    ]
