# Generated by Django 6.0.6 on 2026-08-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_backfill_employment_type_requires_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberingsequence',
            name='year_digits',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 digit (26)'), (4, '4 digit (2026)')], default=4),
        ),
    ]
