# Generated by Django 6.0.6 on 2026-08-12 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_data_scope_level_role_data_scope_mode_and_more'),
        ('administration', '0024_numberingsequence_year_digits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action_type', models.CharField(help_text='Jenis perubahan yang diatur baris ini. Satu baris satu jenis — kenaikan gaji dan perpanjangan kontrak memang diusulkan orang yang berbeda.', max_length=40)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('initiator_type', models.CharField(choices=[('any', 'Anyone With Permission'), ('manager', 'Direct Manager'), ('department_head', 'Department Head'), ('role', 'Role Holder'), ('employee', 'The Employee')], default='any', help_text='Orang yang usulannya sah untuk jenis ini. Dinilai terhadap pegawai yang datanya diubah, bukan terhadap yang mengetik dokumennya.', max_length=20)),
                ('allow_on_behalf', models.BooleanField(default=True, help_text='HR boleh mengetikkan dokumennya untuk pengusul yang menyampaikan lisan, asalkan kolom Requested By diisi. Matikan kalau usulannya harus dibuat sendiri oleh yang bersangkutan.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua company yang tidak punya aturannya sendiri.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_action_policies', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee_group', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua golongan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_action_policies', to='administration.employeegroup')),
                ('initiator_role', models.ForeignKey(blank=True, help_text='Wajib diisi kalau pengusulnya ditentukan lewat Role.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_action_policies', to='accounts.role')),
                ('location', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua lokasi. Diisi kalau site tertentu punya jalur usulan sendiri.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_action_policies', to='administration.location')),
                ('on_behalf_role', models.ForeignKey(blank=True, help_text='Yang boleh mengetikkan atas nama orang lain. Dikosongkan = siapa pun yang punya izin membuat Employee Action.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='on_behalf_action_policies', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Action Policy',
                'verbose_name_plural': 'Employee Action Policies',
                'ordering': ['action_type', 'sort_order', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_employee_action_policy_code')],
            },
        ),
    ]
