# Generated by Django 6.0.6 on 2026-08-12 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_data_scope_level_role_data_scope_mode_and_more'),
        ('administration', '0027_drop_seeded_favorite_menus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDataPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(choices=[('history_salary', 'Salary History'), ('history_separation', 'Resignation & Termination History'), ('history_movement', 'Transfer & Promotion History'), ('history_contract', 'Contract & Status History')], help_text='Kelompok data yang dibatasi baris ini. Kelompok yang tidak punya baris di sini tetap terlihat oleh siapa pun yang datanya masuk cakupannya.', max_length=40)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('allow_self', models.BooleanField(default=True, help_text='Pegawainya sendiri. Gajinya sendiri bukan rahasia darinya, jadi hampir tidak pernah ada alasan mematikannya.')),
                ('allow_manager', models.BooleanField(default=True, help_text='Atasan langsung pegawai (`reports_to`).')),
                ('manager_levels', models.PositiveSmallIntegerField(default=1, help_text='Berapa tingkat garis pelaporan yang ikut boleh melihat. 1 = atasan langsung saja, 2 = sampai atasannya atasan.')),
                ('allow_department_head', models.BooleanField(default=False, help_text='Pemegang jabatan bertanda Manager di department pegawai itu. Perlu diketahui: kepala departemen **tidak** punya cakupan lokasi — di tenant yang satu departemennya tersebar di beberapa site, ini membuka data lintas site.')),
                ('is_active', models.BooleanField(default=True, help_text='Dimatikan = aturannya diabaikan, dan kelompok ini kembali terlihat oleh siapa pun yang datanya masuk cakupannya.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua company yang tidak punya aturannya sendiri.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_data_policies', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee_group', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua golongan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_data_policies', to='administration.employeegroup')),
                ('location', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua lokasi. Diisi kalau site tertentu punya aturan kerahasiaannya sendiri.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_data_policies', to='administration.location')),
                ('role', models.ForeignKey(blank=True, help_text='Role yang boleh melihat, mis. HR-MANAGER. Dikosongkan = tidak ada role yang ditambahkan di luar tiga pilihan di atas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_data_policies', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Data Policy',
                'verbose_name_plural': 'Employee Data Policies',
                'ordering': ['subject', 'sort_order', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_employee_data_policy_code')],
            },
        ),
    ]
