# Generated by Django 6.0.6 on 2026-08-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0028_employeedatapolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedatapolicy',
            name='subject',
            field=models.CharField(choices=[('history_salary', 'Salary History'), ('history_separation', 'Resignation & Termination History'), ('history_movement', 'Transfer & Promotion History'), ('history_contract', 'Contract & Status History'), ('field_identity', 'Identity Numbers (NIK, NPWP, Passport)'), ('field_payroll', 'Payroll & Salary'), ('field_bank', 'Bank Accounts'), ('field_family', 'Family'), ('field_medical', 'Medical'), ('field_document', 'Documents')], help_text='Kelompok data yang dibatasi baris ini. Kelompok yang tidak punya baris di sini tetap terlihat oleh siapa pun yang datanya masuk cakupannya.', max_length=40),
        ),
    ]
