# Generated by Django 6.0.6 on 2026-08-13 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0029_alter_employeedatapolicy_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('late_tolerance_minutes', models.PositiveSmallIntegerField(default=0, help_text='Datang dalam batas ini masih dihitung hadir tepat waktu. Jam tap yang sebenarnya tetap tersimpan apa adanya — yang dipengaruhi hanya status dan menit keterlambatannya.')),
                ('late_counts_from_tolerance', models.BooleanField(default=True, help_text='Menyala: menit telat dihitung dari batas toleransi (toleransi 15, datang 20 → telat 5). Mati: dihitung dari jam jadwal (→ telat 20), jadi toleransi hanya menentukan status. Pilih yang sesuai cara payroll memotongnya.')),
                ('early_leave_tolerance_minutes', models.PositiveSmallIntegerField(default=0, help_text='Pulang lebih awal dalam batas ini tidak dihitung sebagai pulang cepat.')),
                ('overtime_threshold_minutes', models.PositiveSmallIntegerField(default=30, help_text='Lewat jadwal minimal sekian menit baru dihitung lembur. Tanpa ambang, kolom lembur terisi satu-dua menit di hampir setiap baris dan lembur sungguhan tidak bisa dibedakan dari derau.')),
                ('overtime_rounding_minutes', models.PositiveSmallIntegerField(default=0, help_text='Pembulatan ke bawah, mis. 30 berarti 95 menit dihitung 90. Dikosongkan (0) = tanpa pembulatan.')),
                ('break_minutes', models.PositiveSmallIntegerField(default=60, help_text='Potongan istirahat untuk menghitung jam kerja bersih, dipakai kalau catatannya tidak membawa angka sendiri.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua company yang tidak punya aturannya sendiri.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee_group', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua golongan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='administration.employeegroup')),
                ('location', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua lokasi. Diisi untuk membedakan kantor pusat dari site — inilah pembeda yang paling sering dipakai.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='administration.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Policy',
                'verbose_name_plural': 'Attendance Policies',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_attendance_policy_code')],
            },
        ),
    ]
