# Generated by Django 6.0.6 on 2026-08-14 07:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0030_attendancepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='early_leave_leave_threshold_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text="Pulang lebih awal dari sekian menit dianggap mengambil cuti sebesar 'Leave Deduction'. Dikosongkan (0) = tidak dipakai."),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='late_leave_threshold_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text="Telat lebih dari sekian menit dianggap mengambil cuti sebesar 'Leave Deduction'. Dihitung dari jam jadwal, bukan dari batas toleransi. Dikosongkan (0) = tidak dipakai."),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='leave_deduction_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Berapa hari cuti yang harus diambil begitu salah satu ambang di atas terlampaui. Bawaannya setengah hari.', max_digits=4),
        ),
    ]
