# Generated by Django 6.0.6 on 2026-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0031_attendancepolicy_early_leave_leave_threshold_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='carry_over_reminder_days',
            field=models.CharField(blank=True, default='30,14,7', help_text='Sisa hari saat pegawai diingatkan bahwa cuti bawaannya akan hangus, dipisah koma. Dikosongkan = tidak ada pengingat. Ditaruh di sini, bukan di setelan sistem, karena yang menciptakan tanggal hangusnya adalah aturan ini.', max_length=100),
        ),
    ]
