# Generated by Django 6.0.6 on 2026-08-16 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_leavepolicy_carry_over_reminder_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='leave_type',
            field=models.ForeignKey(blank=True, help_text='Jenis cuti yang diterbitkan saat kewajiban ini ditindaklanjuti.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_policies', to='administration.leavetype'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='notify_employee',
            field=models.BooleanField(default=True, help_text='Beri tahu pegawainya saat pengecualian terdeteksi.'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='notify_hr',
            field=models.BooleanField(default=False, help_text='Beri tahu HR juga. Dimatikan bawaannya: di tenant besar ini menghasilkan puluhan surat sehari untuk hal yang sudah ditangani atasannya.'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='notify_supervisor',
            field=models.BooleanField(default=True, help_text='Beri tahu atasan langsung (Reports To pegawainya). Bukan field supervisor tersendiri — garis pelaporan yang sudah ada yang dipakai.'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='require_supervisor_review',
            field=models.BooleanField(default=True, help_text='Kewajiban cuti harus ditinjau atasan langsung sebelum ditindaklanjuti. Dimatikan = HR langsung yang memutuskan.'),
        ),
    ]
