# Generated by Django 6.0.6 on 2026-08-17 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0034_visitpurpose_visittype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('aid', models.CharField(blank=True, db_index=True, default='', help_text="Kode wilayah Kemendagri, disimpan persis seperti di sumber (mis. '11.01.01').", max_length=20, verbose_name='Area ID')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'master_district',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('aid', models.CharField(blank=True, db_index=True, default='', help_text="Kode wilayah Kemendagri, disimpan persis seperti di sumber (mis. '11.01.01.2002').", max_length=20, verbose_name='Area ID')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'db_table': 'master_village',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='aid',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Kode wilayah Kemendagri, disimpan persis seperti di sumber (mis. '11.01'). Awalannya yang menentukan induk — bukan namanya.", max_length=20, verbose_name='Area ID'),
        ),
        migrations.AddField(
            model_name='province',
            name='aid',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Kode wilayah Kemendagri, disimpan persis seperti di sumber (mis. '11'). Ini identitas baris saat import — jangan diubah jadi angka, leading zero-nya bermakna.", max_length=20, verbose_name='Area ID'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('aid', ''), _negated=True)), fields=('aid',), name='uniq_active_administration_city_aid'),
        ),
        migrations.AddConstraint(
            model_name='province',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('aid', ''), _negated=True)), fields=('aid',), name='uniq_active_administration_province_aid'),
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='administration.city'),
        ),
        migrations.AddField(
            model_name='district',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='village',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='village',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='village',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='administration.district'),
        ),
        migrations.AddField(
            model_name='village',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('city', 'code'), name='uniq_active_administration_district_city_code'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('aid', ''), _negated=True)), fields=('aid',), name='uniq_active_administration_district_aid'),
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('district', 'code'), name='uniq_active_administration_village_district_code'),
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('aid', ''), _negated=True)), fields=('aid',), name='uniq_active_administration_village_aid'),
        ),
    ]
