# Generated by Django 6.0.6 on 2026-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0035_district_village_city_aid_province_aid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='document_required',
            field=models.BooleanField(default=False, help_text='Pengajuan wajib melampirkan dokumen pendukung — surat dokter, surat nikah, akta.'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='history_action',
            field=models.CharField(choices=[('none', 'None'), ('warn', 'Warning'), ('review', 'Warning + Review'), ('block', 'Block')], default='none', help_text='Warning = ditampilkan saja. Warning + Review = ikut terbawa sampai meja persetujuan terakhir. Block = pengajuannya ditolak.', max_length=20),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='history_check',
            field=models.BooleanField(default=False, help_text='Periksa riwayat penggunaan jenis cuti ini saat request dibuat, lalu tampilkan temuannya. Yang menentukan akibatnya kolom di bawah.'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='max_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maksimum hari yang boleh digunakan untuk satu request/event. Dikosongkan = tanpa batas — dipakai cuti yang lamanya ditentukan surat dokter atau keterangan resmi, bukan oleh perusahaan.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='per_event',
            field=models.BooleanField(default=False, help_text='Hak berlaku per kejadian, bukan sebagai saldo tahunan. Menyala: dua kelahiran anak masing-masing berhak penuh, dan yang diperiksa riwayatnya adalah kejadiannya.'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='uses_balance',
            field=models.BooleanField(default=True, help_text='Jika aktif, policy menerbitkan dan menggunakan LeaveBalance. Dimatikan untuk cuti yang haknya per kejadian — cutinya tetap dicatat, tapi tidak ada saldo yang dipotong.'),
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='entitlement_days',
            field=models.DecimalField(decimal_places=2, default=12, help_text='Jatah penuh untuk satu periode, mis. 12 hari setahun. Tidak berpengaruh apa-apa saat Uses Balance dimatikan.', max_digits=6),
        ),
    ]
