# Generated by Django 6.0.6 on 2026-08-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0036_leavepolicy_document_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroup',
            name='attendance_applicable',
            field=models.BooleanField(default=True, help_text='Pegawai group ini jadi subjek Attendance — jadwal, penutupan hari, dan penandaan mangkir.'),
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='field_break_applicable',
            field=models.BooleanField(default=True, help_text='Pegawai group ini punya blok Field Break — kepulangan site lewat Travel Request.'),
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='leave_applicable',
            field=models.BooleanField(default=True, help_text='Pegawai group ini memakai proses Cuti — saldo, pengajuan, dan persetujuan.'),
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='overtime_applicable',
            field=models.BooleanField(default=True, help_text='Pegawai group ini bisa mengajukan/dicatatkan Lembur.'),
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='roster_applicable',
            field=models.BooleanField(default=True, help_text='Pegawai group ini ikut Roster — muncul sebagai kandidat Roster Setup dan Roster Assignment.'),
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='shift_applicable',
            field=models.BooleanField(default=True, help_text='Pegawai group ini memakai Shift pada pola kerjanya.'),
        ),
    ]
