# Generated by Django 6.0.6 on 2026-08-28 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0037_employeegroup_feature_applicability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterShiftRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField(help_text='Urutan langkah perputaran. Sesudah langkah terakhir, perputaran kembali ke langkah pertama.')),
                ('block_days', models.PositiveSmallIntegerField(default=7, help_text='Berapa hari shift ini dipakai sebelum berganti ke langkah berikutnya. 7 = mingguan.')),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rotations', to='administration.rosterpolicy')),
                ('shift', models.ForeignKey(help_text='Jam kerjanya milik master Shift — mengubah jam di sana mengubah jadwal semua yang memakai pola ini.', on_delete=django.db.models.deletion.PROTECT, related_name='roster_shift_rotations', to='administration.shift')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_roster_shift_rotation',
                'ordering': ['policy', 'sequence'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('policy', 'sequence'), name='uniq_active_rostershiftrotation_sequence')],
            },
        ),
    ]
