# Generated by Django 6.0.6 on 2026-09-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0038_rostershiftrotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterpolicy',
            name='min_rest_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='Jeda istirahat minimum saat shift berganti, dalam jam — dihitung dari jam selesai shift terakhir sampai jam mulai shift berikutnya. Generator menyisipkan hari Recovery sampai jeda ini terpenuhi. 0 = tidak diperiksa.'),
        ),
    ]
