# Generated by Django 6.0.6 on 2026-09-05 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0039_rosterpolicy_min_rest_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_holiday_company',
                'ordering': ['company__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='holiday',
            name='uniq_core_holiday_company_location_date',
        ),
        migrations.RemoveConstraint(
            model_name='workcalendar',
            name='uniq_core_work_calendar_company_code',
        ),
        migrations.AddField(
            model_name='holiday',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='holiday',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='holiday',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'National / All Companies'), ('COMPANY', 'Company'), ('LOCATION', 'Location'), ('SELECTED_COMPANIES', 'Selected Companies')], db_index=True, default='COMPANY', max_length=20),
        ),
        migrations.AddField(
            model_name='holiday',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Import'), ('GOOGLE', 'Google Calendar'), ('GOVERNMENT', 'Government'), ('ICS', 'ICS Feed')], db_index=True, default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='holiday',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='holiday',
            name='sync_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending Review'), ('REJECTED', 'Rejected')], db_index=True, default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='holiday',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workcalendar',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'All Companies'), ('COMPANY', 'Company'), ('LOCATION', 'Location')], db_index=True, default='COMPANY', max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='administration.company'),
        ),
        migrations.AlterField(
            model_name='workcalendar',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_calendars', to='administration.company'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'location', 'date', 'code'), name='uniq_active_holiday_scope_date_code', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='workcalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'location', 'code'), name='uniq_active_work_calendar_scope_code', nulls_distinct=False),
        ),
        migrations.AddField(
            model_name='holidaycompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_holidays', to='administration.company'),
        ),
        migrations.AddField(
            model_name='holidaycompany',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holidaycompany',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holidaycompany',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='administration.holiday'),
        ),
        migrations.AddField(
            model_name='holidaycompany',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='holidaycompany',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('holiday', 'company'), name='uniq_active_holiday_company'),
        ),
    ]
