# Generated by Django 6.0.6 on 2026-09-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    # **Bergantung pada migrasi penyalinan, dan itu bukan kerapian.**
    # Tanpa baris ini urutannya ditentukan abjad nama app, dan
    # `administration` berjalan sebelum `finance` — tabelnya terhapus
    # sebelum satu baris pun sempat disalin. Preseden yang sama
    # persis dengan `framework.0003` yang bergantung pada
    # `workflow.0002_migrate_framework_approval`.
    dependencies = [
        ('administration', '0041_backfill_calendar_scope'),
        ('finance', '0002_adopt_administration_fiscal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fiscalyear',
            name='uniq_core_fiscal_year_company_code',
        ),
        migrations.RemoveConstraint(
            model_name='fiscalyear',
            name='uniq_core_fiscal_year_company_year',
        ),
        migrations.RemoveConstraint(
            model_name='postingperiod',
            name='uniq_core_posting_period_fiscal_year_code',
        ),
        migrations.RemoveField(
            model_name='postingperiod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postingperiod',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='postingperiod',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='postingperiod',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='postingperiod',
            name='unlocked_by',
        ),
        migrations.RemoveField(
            model_name='postingperiod',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='FiscalYear',
        ),
        migrations.DeleteModel(
            name='PostingPeriod',
        ),
    ]
