# Generated by Django 6.0.6 on 2026-09-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0042_move_fiscal_year_to_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroup',
            name='business_trip_applicable',
            field=models.BooleanField(default=True, help_text='Pegawai group ini boleh mengajukan Business Trip (perjalanan dinas).'),
        ),
    ]
