# Generated by Django 6.0.6 on 2026-10-01 07:04

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0043_employeegroup_business_trip_applicable'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='requires_serial_number',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('tag_number', models.CharField(blank=True, default='', max_length=100)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_reference', models.CharField(blank=True, default='', max_length=150)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable')], default='GOOD', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], db_index=True, default='DRAFT', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='administration.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='administration.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets_asset',
                'ordering': ['company', 'asset_code'],
            },
        ),
        migrations.CreateModel(
            name='AssetCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('custody_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ORGANIZATION', 'Organization'), ('STORAGE', 'Storage')], max_length=20)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('start_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable')], max_length=20)),
                ('end_condition', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable')], default='', max_length=20)),
                ('opened_by_type', models.CharField(max_length=50)),
                ('opened_by_id', models.CharField(max_length=50)),
                ('closed_by_type', models.CharField(blank=True, default='', max_length=50)),
                ('closed_by_id', models.CharField(blank=True, default='', max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodies', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_custodies', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_custodies', to='administration.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_custodies', to='administration.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Custody',
                'verbose_name_plural': 'Asset Custodies',
                'db_table': 'assets_asset_custody',
                'ordering': ['asset', 'started_on', 'id'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='current_custody',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetcustody'),
        ),
        migrations.CreateModel(
            name='AssetConditionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_condition', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable')], default='', max_length=20)),
                ('new_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable')], max_length=20)),
                ('source', models.CharField(choices=[('REGISTRATION', 'Registration'), ('INSPECTION', 'Inspection')], max_length=20)),
                ('effective_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_logs', to='assets.asset')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Condition Log',
                'verbose_name_plural': 'Asset Condition Logs',
                'db_table': 'assets_asset_condition_log',
                'ordering': ['asset', 'effective_at', 'id'],
                'indexes': [models.Index(fields=['asset', 'effective_at'], name='idx_assets_condlog_asset_at')],
            },
        ),
        migrations.AddIndex(
            model_name='assetcustody',
            index=models.Index(fields=['location', 'ended_on'], name='idx_assets_custody_loc_open'),
        ),
        migrations.AddConstraint(
            model_name='assetcustody',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True), ('is_deleted', False)), fields=('asset',), name='uniq_open_assets_custody_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetcustody',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='ck_assets_custody_period'),
        ),
        migrations.AddConstraint(
            model_name='assetcustody',
            constraint=models.CheckConstraint(condition=models.Q(('custody_type', 'STORAGE')), name='ck_assets_custody_storage_only'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'status'], name='idx_asset_company_status'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['location', 'status'], name='idx_asset_location_status'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'asset_code'), name='uniq_active_assets_asset_company_code'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Upper('serial_number'), condition=models.Q(('is_deleted', False), models.Q(('serial_number', ''), _negated=True)), name='uniq_active_assets_asset_company_serial'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Upper('tag_number'), condition=models.Q(('is_deleted', False), models.Q(('tag_number', ''), _negated=True)), name='uniq_active_assets_asset_company_tag'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('asset_code', ''), _negated=True), name='ck_assets_asset_code_present'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_custody__isnull', True), ('status', 'DRAFT')), models.Q(('current_custody__isnull', False), ('status', 'ACTIVE')), _connector='OR'), name='ck_assets_asset_status_custody'),
        ),
    ]
