# Generated by Django 6.0.6 on 2026-10-01 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0043_employeegroup_business_trip_applicable'),
        ('assets', '0002_asset_register'),
        ('hr', '0062_employeeattendance_business_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('target_custody_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ORGANIZATION', 'Organization')], max_length=20)),
                ('is_cross_company', models.BooleanField(default=False)),
                ('cross_company_reason', models.TextField(blank=True, default='')),
                ('purpose', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('handover_condition', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable')], default='', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asset Assignment',
                'verbose_name_plural': 'Asset Assignments',
                'db_table': 'assets_asset_assignment',
                'ordering': ['-created_at', '-id'],
                'permissions': [('submit_assetassignment', 'Can submit asset assignment'), ('complete_assetassignment', 'Can complete asset assignment'), ('cancel_assetassignment', 'Can cancel asset assignment')],
            },
        ),
        migrations.RemoveConstraint(
            model_name='assetcustody',
            name='ck_assets_custody_storage_only',
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='allow_employee_custody',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='allow_organization_custody',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assetcustody',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_custodies', to='administration.department'),
        ),
        migrations.AddField(
            model_name='assetcustody',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_custodies', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assetcustody',
            name='pic_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_pic_custodies', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='assetconditionlog',
            name='source',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('INSPECTION', 'Inspection'), ('HANDOVER', 'Handover')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='assetcustody',
            index=models.Index(fields=['employee', 'ended_on'], name='idx_assets_custody_emp_open'),
        ),
        migrations.AddIndex(
            model_name='assetcustody',
            index=models.Index(fields=['pic_employee', 'ended_on'], name='idx_assets_custody_pic_open'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('allow_employee_custody', True), ('allow_organization_custody', True), _connector='OR'), name='ck_assets_category_some_custody'),
        ),
        migrations.AddConstraint(
            model_name='assetcustody',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custody_type', 'STORAGE'), ('department__isnull', True), ('employee__isnull', True), ('pic_employee__isnull', True)), models.Q(('custody_type', 'EMPLOYEE'), ('department__isnull', True), ('employee__isnull', False), ('pic_employee__isnull', True)), models.Q(('custody_type', 'ORGANIZATION'), ('department__isnull', False), ('employee__isnull', True)), _connector='OR'), name='ck_assets_custody_holder_shape'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='administration.company'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='administration.department'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='employee_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.company'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='employee_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.department'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='employee_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.location'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='administration.facility'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='administration.location'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='pic_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_pic_assignments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='resulting_custody',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetcustody'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='source_custody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetcustody'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.location'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['company', 'status'], name='idx_assets_assign_co_status'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['employee', 'status'], name='idx_assets_assign_emp_status'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('document_number', ''), _negated=True)), fields=('company', 'document_number'), name='uniq_active_assets_assignment_number'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ('SUBMITTED', 'APPROVED'))), fields=('asset',), name='uniq_inflight_assets_assignment_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('employee__isnull', False), ('pic_employee__isnull', True), ('target_custody_type', 'EMPLOYEE')), models.Q(('department__isnull', False), ('employee__isnull', True), ('target_custody_type', 'ORGANIZATION')), _connector='OR'), name='ck_assets_assignment_target_shape'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), models.Q(('handover_date__isnull', False), ('resulting_custody__isnull', False)), _connector='OR'), name='ck_assets_assignment_completed_has_custody'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.CheckConstraint(condition=models.Q(('is_cross_company', False), models.Q(('cross_company_reason', ''), _negated=True), _connector='OR'), name='ck_assets_assignment_cross_company_reason'),
        ),
    ]
