# Generated by Django 6.0.6 on 2026-10-01 08:07
#
# ASSET-4: pemesanan bersama (`AssetOperationReservation`) + `AssetReturn`.
#
# Urutan disengaja: tabel pemesanan dan constraint-nya dibuat lebih dulu,
# lalu Assignment yang sedang berjalan (SUBMITTED/APPROVED) dipindahkan ke
# sana, **baru** `uniq_inflight_assets_assignment_asset` dilepas — tidak
# ada saat di mana aset tanpa penjaga pemesanan, dan tidak ada dua
# authority sesudahnya.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def move_inflight_assignments(apps, schema_editor):
    """
    Setiap Assignment SUBMITTED/APPROVED mendapat pemesanan terbuka.
    `uniq_inflight_assets_assignment_asset` menjamin paling banyak satu per
    aset, jadi constraint pemesanan yang baru tidak bisa dilanggar di sini.
    """
    Assignment = apps.get_model("assets", "AssetAssignment")
    Reservation = apps.get_model("assets", "AssetOperationReservation")

    inflight = (
        Assignment.objects
        .filter(is_deleted=False, status__in=("SUBMITTED", "APPROVED"))
        .order_by("pk")
    )

    Reservation.objects.bulk_create([
        Reservation(
            asset_id=row.asset_id,
            operation_type="ASSIGNMENT",
            document_id=row.pk,
            document_number=row.document_number,
            reserved_at=row.submitted_at or timezone.now(),
            reserved_by_id=row.updated_by_id,
        )
        for row in inflight
    ])


def restore_inflight_assignments(apps, schema_editor):
    # Mundur: constraint lama dipasang kembali oleh operasi sesudahnya;
    # pemesanan Assignment dibuang bersama tabelnya.
    Reservation = apps.get_model("assets", "AssetOperationReservation")
    Reservation.objects.filter(operation_type="ASSIGNMENT").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0043_employeegroup_business_trip_applicable'),
        ('assets', '0003_asset_assignment'),
        ('hr', '0062_employeeattendance_business_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOperationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('document_id', models.BigIntegerField()),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('reserved_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('RETURNED_TO_DRAFT', 'Returned to draft')], default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Asset Operation Reservation',
                'verbose_name_plural': 'Asset Operation Reservations',
                'db_table': 'assets_asset_operation_reservation',
                'ordering': ['asset', 'reserved_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssetReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('source_custody_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ORGANIZATION', 'Organization')], max_length=20)),
                ('reason', models.CharField(choices=[('END_OF_USE', 'End of use'), ('SEPARATION', 'Separation'), ('REPLACEMENT', 'Replacement'), ('DAMAGE', 'Damage'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable')], default='', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asset Return',
                'verbose_name_plural': 'Asset Returns',
                'db_table': 'assets_asset_return',
                'ordering': ['-created_at', '-id'],
                'permissions': [('submit_assetreturn', 'Can submit asset return'), ('complete_assetreturn', 'Can complete asset return'), ('cancel_assetreturn', 'Can cancel asset return')],
            },
        ),
        migrations.AlterField(
            model_name='assetconditionlog',
            name='source',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('INSPECTION', 'Inspection'), ('HANDOVER', 'Handover'), ('RETURN', 'Return')], max_length=20),
        ),
        migrations.AddField(
            model_name='assetoperationreservation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_reservations', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetoperationreservation',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetoperationreservation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_returns', to='administration.company'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='destination_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_returns', to='administration.facility'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_returns', to='administration.location'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='resulting_custody',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetcustody'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='source_custody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetcustody'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='source_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.department'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='source_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_returns', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='source_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.facility'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.location'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='source_pic_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assetoperationreservation',
            index=models.Index(fields=['operation_type', 'document_id'], name='idx_assets_reserv_document'),
        ),
        migrations.AddConstraint(
            model_name='assetoperationreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('asset',), name='uniq_active_assets_reservation_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetoperationreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('operation_type', 'document_id'), name='uniq_active_assets_reservation_document'),
        ),
        migrations.AddConstraint(
            model_name='assetoperationreservation',
            constraint=models.CheckConstraint(condition=models.Q(('operation_type__in', ['ASSIGNMENT', 'RETURN', 'TRANSFER'])), name='ck_assets_reservation_operation_type'),
        ),
        migrations.AddConstraint(
            model_name='assetoperationreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('release_reason', ''), ('released_at__isnull', True)), models.Q(('released_at__isnull', False), models.Q(('release_reason', ''), _negated=True), ('released_at__gte', models.F('reserved_at'))), _connector='OR'), name='ck_assets_reservation_release_shape'),
        ),
        migrations.AddIndex(
            model_name='assetreturn',
            index=models.Index(fields=['company', 'status'], name='idx_assets_return_co_status'),
        ),
        migrations.AddIndex(
            model_name='assetreturn',
            index=models.Index(fields=['source_employee', 'status'], name='idx_assets_return_emp_status'),
        ),
        migrations.AddConstraint(
            model_name='assetreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('document_number', ''), _negated=True)), fields=('company', 'document_number'), name='uniq_active_assets_return_number'),
        ),
        migrations.AddConstraint(
            model_name='assetreturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_custody_type', 'EMPLOYEE'), ('source_department__isnull', True), ('source_employee__isnull', False), ('source_pic_employee__isnull', True)), models.Q(('source_custody_type', 'ORGANIZATION'), ('source_department__isnull', False), ('source_employee__isnull', True)), _connector='OR'), name='ck_assets_return_source_shape'),
        ),
        migrations.AddConstraint(
            model_name='assetreturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), models.Q(('resulting_custody__isnull', False), ('return_date__isnull', False), models.Q(('return_condition', ''), _negated=True)), _connector='OR'), name='ck_assets_return_completed_has_custody'),
        ),
        migrations.RunPython(
            move_inflight_assignments,
            restore_inflight_assignments,
        ),
        migrations.RemoveConstraint(
            model_name='assetassignment',
            name='uniq_inflight_assets_assignment_asset',
        ),
    ]
