# Generated by Django 6.0.6 on 2026-10-01 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0043_employeegroup_business_trip_applicable'),
        ('assets', '0004_asset_return_reservation'),
        ('hr', '0062_employeeattendance_business_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetconditionlog',
            name='source',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('INSPECTION', 'Inspection'), ('HANDOVER', 'Handover'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer')], max_length=20),
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('source_custody_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ORGANIZATION', 'Organization'), ('STORAGE', 'Storage')], max_length=20)),
                ('target_custody_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ORGANIZATION', 'Organization'), ('STORAGE', 'Storage')], max_length=20)),
                ('is_cross_company', models.BooleanField(default=False)),
                ('cross_company_reason', models.TextField(blank=True, default='')),
                ('reason', models.CharField(choices=[('REASSIGNMENT', 'Reassignment'), ('PIC_CHANGE', 'PIC change'), ('RELOCATION', 'Relocation'), ('REORGANIZATION', 'Reorganization'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_condition', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable')], default='', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers', to='administration.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.company')),
                ('employee_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.department')),
                ('employee_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.location')),
                ('resulting_custody', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetcustody')),
                ('source_custody', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetcustody')),
                ('source_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.department')),
                ('source_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_out', to='hr.employee')),
                ('source_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.facility')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='administration.location')),
                ('source_pic_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.employee')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_in', to='administration.department')),
                ('target_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_in', to='hr.employee')),
                ('target_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_in', to='administration.facility')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_in', to='administration.location')),
                ('target_pic_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_pic_transfers_in', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Transfer',
                'verbose_name_plural': 'Asset Transfers',
                'db_table': 'assets_asset_transfer',
                'ordering': ['-created_at', '-id'],
                'permissions': [('submit_assettransfer', 'Can submit asset transfer'), ('complete_assettransfer', 'Can complete asset transfer'), ('cancel_assettransfer', 'Can cancel asset transfer')],
                'indexes': [models.Index(fields=['company', 'status'], name='idx_assets_transfer_co_status'), models.Index(fields=['source_employee', 'status'], name='idx_assets_transfer_src_emp'), models.Index(fields=['target_employee', 'status'], name='idx_assets_transfer_tgt_emp')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('document_number', ''), _negated=True)), fields=('company', 'document_number'), name='uniq_active_assets_transfer_number'), models.CheckConstraint(condition=models.Q(models.Q(('source_custody_type', 'STORAGE'), ('source_department__isnull', True), ('source_employee__isnull', True), ('source_pic_employee__isnull', True)), models.Q(('source_custody_type', 'EMPLOYEE'), ('source_department__isnull', True), ('source_employee__isnull', False), ('source_pic_employee__isnull', True)), models.Q(('source_custody_type', 'ORGANIZATION'), ('source_department__isnull', False), ('source_employee__isnull', True)), _connector='OR'), name='ck_assets_transfer_source_shape'), models.CheckConstraint(condition=models.Q(models.Q(('target_custody_type', 'STORAGE'), ('target_department__isnull', True), ('target_employee__isnull', True), ('target_pic_employee__isnull', True)), models.Q(('target_custody_type', 'EMPLOYEE'), ('target_department__isnull', True), ('target_employee__isnull', False), ('target_pic_employee__isnull', True)), models.Q(('target_custody_type', 'ORGANIZATION'), ('target_department__isnull', False), ('target_employee__isnull', True)), _connector='OR'), name='ck_assets_transfer_target_shape'), models.CheckConstraint(condition=models.Q(models.Q(('source_custody_type', 'STORAGE'), ('target_custody_type', 'STORAGE')), models.Q(('source_custody_type__in', ('EMPLOYEE', 'ORGANIZATION')), ('target_custody_type__in', ('EMPLOYEE', 'ORGANIZATION'))), _connector='OR'), name='ck_assets_transfer_same_phase'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), models.Q(('resulting_custody__isnull', False), ('transfer_date__isnull', False), models.Q(('transfer_condition', ''), _negated=True)), _connector='OR'), name='ck_assets_transfer_completed_has_custody'), models.CheckConstraint(condition=models.Q(('is_cross_company', False), models.Q(('cross_company_reason', ''), _negated=True), _connector='OR'), name='ck_assets_transfer_cross_company_reason')],
            },
        ),
    ]
