# Generated by Django 6.0.6 on 2026-08-07 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_allowancetemplate_deductiontemplate_overtimegroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancetemplate',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='deductiontemplate',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='overtimegroup',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='payrollgroup',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='taxstatus',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='allowancetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_payroll_allowancetemplate_code'),
        ),
        migrations.AddConstraint(
            model_name='deductiontemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_payroll_deductiontemplate_code'),
        ),
        migrations.AddConstraint(
            model_name='overtimegroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_payroll_overtimegroup_code'),
        ),
        migrations.AddConstraint(
            model_name='payrollgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_payroll_payrollgroup_code'),
        ),
        migrations.AddConstraint(
            model_name='salarygrade',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_payroll_salarygrade_code'),
        ),
        migrations.AddConstraint(
            model_name='taxstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_payroll_taxstatus_code'),
        ),
    ]
