# Generated by Django 6.0.6 on 2026-09-03 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0039_rosterpolicy_min_rest_hours'),
        ('payroll', '0004_overtimegroup_hourly_divisor_allowancetemplateline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrunemployee',
            name='proration_base_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='proration_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('proration_method', models.CharField(choices=[('fixed_30', 'Fixed 30 Days'), ('calendar_days', 'Calendar Days'), ('working_days', 'Working Days')], default='calendar_days', help_text='Cara gaji sebulan dipecah jadi hak harian untuk pegawai yang masuk atau berhenti di tengah periode.', max_length=20)),
                ('prorate_on_join', models.BooleanField(default=True, help_text='Pegawai yang masuk di tengah periode dibayar sejak tanggal masuknya saja. Dimatikan berarti ia menerima gaji sebulan penuh.')),
                ('prorate_on_termination', models.BooleanField(default=True, help_text='Pegawai yang berhenti di tengah periode dibayar sampai hari terakhirnya saja. Dimatikan berarti ia menerima gaji sebulan penuh.')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_setting', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Setting',
                'verbose_name_plural': 'Payroll Settings',
                'db_table': 'payroll_setting',
                'ordering': ['company__name'],
            },
        ),
    ]
