# Generated by Django 6.0.6 on 2026-09-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollrunemployee_proration_base_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrunemployee',
            name='absence_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='attendance_deduction_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='deduction_base_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='unpaid_leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='attendance_deduction_method',
            field=models.CharField(blank=True, choices=[('fixed_30', 'Fixed 30 Days'), ('calendar_days', 'Calendar Days'), ('working_days', 'Working Days')], default='', help_text='Pembagi yang dipakai menghitung nilai sehari untuk potongan absen dan cuti tidak dibayar. Dikosongkan berarti mengikuti pembagi hari yang tertulis di periode payroll — perilaku yang berlaku sebelum kebijakan ini ada.', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='deduct_absence',
            field=models.BooleanField(default=True, help_text='Hari yang tercatat alpa di absensi memotong gaji. Dimatikan berarti ketidakhadiran ditangani di luar payroll.'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='deduct_unpaid_leave',
            field=models.BooleanField(default=True, help_text='Hari cuti berjenis tidak dibayar memotong gaji. Jenis cuti mana yang tidak dibayar tetap ditentukan Payroll Leave Rule, bukan di sini.'),
        ),
    ]
