# Generated by Django 6.0.6 on 2026-09-04 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollrunemployee_absence_deduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimegroup',
            name='tier_basis',
            field=models.CharField(blank=True, choices=[('daily', 'Per hari lembur'), ('monthly', 'Total jam sebulan')], default='', help_text='Wajib diisi kalau kelompok ini memakai tingkat. Per hari: tiap hari lembur mulai lagi dari tingkat pertama. Total sebulan: seluruh jam sebulan disusun sekali.', max_length=20),
        ),
        migrations.AlterField(
            model_name='overtimegroup',
            name='hourly_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Pengali upah per jam kalau kelompok ini belum punya tingkat. Diabaikan begitu ada tingkat yang aktif.', max_digits=6),
        ),
        migrations.CreateModel(
            name='OvertimeGroupTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('hour_from', models.DecimalField(decimal_places=2, default=0, help_text='Batas bawah jam lembur kumulatif, ikut terhitung. 0 = mulai dari jam lembur pertama.', max_digits=6)),
                ('hour_to', models.DecimalField(blank=True, decimal_places=2, help_text='Kosong = tingkat teratas, tanpa batas atas.', max_digits=6, null=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, help_text='Pengali upah per jam pada rentang ini, mis. 1,5.', max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='payroll.overtimegroup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overtime Tier',
                'verbose_name_plural': 'Overtime Tiers',
                'db_table': 'payroll_overtime_group_tier',
                'ordering': ['group__code', 'sequence', 'hour_from'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('group', 'sequence'), name='uniq_active_payroll_overtime_tier_sequence')],
            },
        ),
    ]
