# Generated by Django 6.0.6 on 2026-09-04 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0039_rosterpolicy_min_rest_hours'),
        ('payroll', '0007_overtimegroup_tier_basis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrunemployee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='pay_basis',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('pay_basis', models.CharField(choices=[('monthly', 'Bulanan'), ('daily', 'Harian')], default='monthly', help_text='Bulanan: gaji sebulan dipecah jadi hak harian kalau masa kerjanya tidak penuh. Harian: upah dibentuk dari hari yang benar-benar dibayar, jadi tidak ada prorata dan tidak ada potongan ketidakhadiran.', max_length=20)),
                ('proration_method', models.CharField(blank=True, choices=[('fixed_30', 'Fixed 30 Days'), ('calendar_days', 'Calendar Days'), ('working_days', 'Working Days')], default='', help_text='Dikosongkan = ikut kebijakan perusahaan di Payroll Settings.', max_length=20)),
                ('prorate_on_join', models.CharField(choices=[('inherit', 'Ikut kebijakan perusahaan'), ('on', 'Ya'), ('off', 'Tidak')], default='inherit', help_text='Pegawai yang masuk di tengah periode diprorata.', max_length=10)),
                ('prorate_on_termination', models.CharField(choices=[('inherit', 'Ikut kebijakan perusahaan'), ('on', 'Ya'), ('off', 'Tidak')], default='inherit', help_text='Pegawai yang berhenti di tengah periode diprorata.', max_length=10)),
                ('attendance_deduction_method', models.CharField(blank=True, choices=[('fixed_30', 'Fixed 30 Days'), ('calendar_days', 'Calendar Days'), ('working_days', 'Working Days')], default='', help_text='Pembagi nilai sehari untuk potongan absen dan cuti tidak dibayar. Dikosongkan = ikut kebijakan perusahaan.', max_length=20)),
                ('deduct_absence', models.CharField(choices=[('inherit', 'Ikut kebijakan perusahaan'), ('on', 'Ya'), ('off', 'Tidak')], default='inherit', help_text='Hari alpa memotong gaji.', max_length=10)),
                ('deduct_unpaid_leave', models.CharField(choices=[('inherit', 'Ikut kebijakan perusahaan'), ('on', 'Ya'), ('off', 'Tidak')], default='inherit', help_text='Hari cuti berjenis tidak dibayar memotong gaji. Jenis cuti mana yang tidak dibayar tetap ditentukan Payroll Leave Rule.', max_length=10)),
                ('daily_rate_method', models.CharField(blank=True, choices=[('assignment_rate', 'Tarif harian di Payroll Assignment'), ('from_monthly', 'Gaji sebulan dibagi pembagi')], default='', help_text='Wajib diisi kalau dasar perhitungannya Harian. Sistem tidak memilihkan — kedua caranya lazim dan hasilnya berbeda.', max_length=20)),
                ('daily_rate_divisor', models.DecimalField(blank=True, decimal_places=2, help_text='Pembagi gaji sebulan jadi upah sehari, mis. 25 atau 30. Hanya dipakai kalau tarif harian diturunkan dari gaji sebulan.', max_digits=7, null=True)),
                ('pay_paid_leave', models.CharField(blank=True, choices=[('yes', 'Dibayar - hari cuti tetap menghasilkan upah sehari'), ('no', 'Tidak dibayar - hanya hari kerja nyata yang dibayar')], default='', help_text='Wajib diisi kalau dasar perhitungannya Harian. Sistem tidak memilihkan — keduanya lazim dan menentukan apakah seseorang dibayar.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(help_text='Kebijakan ini milik satu perusahaan dan hanya boleh dipakai pegawai perusahaan itu.', on_delete=django.db.models.deletion.CASCADE, related_name='payroll_policies', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Policy',
                'verbose_name_plural': 'Payroll Policies',
                'db_table': 'payroll_policy',
                'ordering': ['company__name', 'code'],
            },
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='payroll_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payroll.payrollpolicy'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'code'), name='uniq_active_payroll_policy_code'),
        ),
    ]
