# Generated by Django 6.0.6 on 2026-09-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payrollrunemployee_daily_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductiontemplateline',
            name='is_employer_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_employer_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='employer_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollruncomponent',
            name='component_type',
            field=models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution')], max_length=30),
        ),
    ]
