# Generated by Django 6.0.6 on 2026-09-05 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0041_backfill_calendar_scope'),
        ('hr', '0056_payrollassignment_payroll_policy'),
        ('payroll', '0009_deductiontemplateline_is_employer_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancetemplateline',
            name='basis',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent_of_basic', '% of Basic Salary'), ('percent_of_gross', '% of Gross Earning'), ('percent_of_taxable', '% of Taxable Earning'), ('per_working_day', 'Amount x Working Day'), ('per_paid_day', 'Amount x Paid Day'), ('per_attendance_day', 'Amount x Attendance Day'), ('per_absent_day', 'Amount x Absent Day'), ('per_unpaid_leave_day', 'Amount x Unpaid Leave Day'), ('per_overtime_hour', 'Amount x Overtime Hour'), ('pph21_progressive', 'PPh21 Progressive'), ('percent_of_resolved_base', '% of Resolved Base')], default='fixed', max_length=30),
        ),
        migrations.AlterField(
            model_name='deductiontemplateline',
            name='basis',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent_of_basic', '% of Basic Salary'), ('percent_of_gross', '% of Gross Earning'), ('percent_of_taxable', '% of Taxable Earning'), ('per_working_day', 'Amount x Working Day'), ('per_paid_day', 'Amount x Paid Day'), ('per_attendance_day', 'Amount x Attendance Day'), ('per_absent_day', 'Amount x Absent Day'), ('per_unpaid_leave_day', 'Amount x Unpaid Leave Day'), ('per_overtime_hour', 'Amount x Overtime Hour'), ('pph21_progressive', 'PPh21 Progressive'), ('percent_of_resolved_base', '% of Resolved Base')], default='fixed', max_length=30),
        ),
        migrations.AlterField(
            model_name='payrollruncomponent',
            name='basis',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent_of_basic', '% of Basic Salary'), ('percent_of_gross', '% of Gross Earning'), ('percent_of_taxable', '% of Taxable Earning'), ('per_working_day', 'Amount x Working Day'), ('per_paid_day', 'Amount x Paid Day'), ('per_attendance_day', 'Amount x Attendance Day'), ('per_absent_day', 'Amount x Absent Day'), ('per_unpaid_leave_day', 'Amount x Unpaid Leave Day'), ('per_overtime_hour', 'Amount x Overtime Hour'), ('pph21_progressive', 'PPh21 Progressive'), ('percent_of_resolved_base', '% of Resolved Base')], default='fixed', max_length=30),
        ),
        migrations.AlterField(
            model_name='payrollruncomponent',
            name='source',
            field=models.CharField(choices=[('basic', 'Basic Salary'), ('allowance_template', 'Allowance Template'), ('deduction_template', 'Deduction Template'), ('overtime', 'Overtime'), ('input', 'Payroll Input'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('tax', 'Tax'), ('bpjs', 'BPJS')], max_length=30),
        ),
        migrations.CreateModel(
            name='BpjsBaseDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Mis. UPAH-POKOK-TETAP.', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('include_basic', models.BooleanField(default=True, help_text='Gaji pokok ikut jadi dasar iuran. Yang dipakai gaji pokok sebulan menurut kontrak, bukan yang sudah diprorata.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BPJS Base Definition',
                'verbose_name_plural': 'BPJS Base Definitions',
                'db_table': 'payroll_bpjs_base_definition',
                'ordering': ['code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='BpjsBaseComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('allowance_code', models.CharField(help_text='Kode komponen tunjangan yang ikut jadi dasar iuran, persis seperti tertulis di Allowance Component.', max_length=30)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.bpjsbasedefinition')),
            ],
            options={
                'verbose_name': 'BPJS Base Component',
                'verbose_name_plural': 'BPJS Base Components',
                'db_table': 'payroll_bpjs_base_component',
                'ordering': ['definition', 'sequence', 'allowance_code'],
            },
        ),
        migrations.CreateModel(
            name='BpjsProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Mis. JKN, JHT, JP, JKK, JKM.', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BPJS Program',
                'verbose_name_plural': 'BPJS Programs',
                'db_table': 'payroll_bpjs_program',
                'ordering': ['sequence', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BpjsEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('participates', models.BooleanField(default=True, help_text='Dimatikan = tidak ikut program ini, tanpa menghapus riwayat kepesertaannya.')),
                ('enrolled_from', models.DateField()),
                ('enrolled_to', models.DateField(blank=True, help_text='Kosong = masih terdaftar.', null=True)),
                ('membership_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpjs_enrollments', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='payroll.bpjsprogram')),
            ],
            options={
                'verbose_name': 'BPJS Enrollment',
                'verbose_name_plural': 'BPJS Enrollments',
                'db_table': 'payroll_bpjs_enrollment',
                'ordering': ['employee', 'program__sequence', '-enrolled_from'],
            },
        ),
        migrations.CreateModel(
            name='BpjsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Kosong = masih berlaku.', null=True)),
                ('employee_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Kosong = program ini tidak dipotong dari pegawai.', max_digits=9, null=True)),
                ('employee_minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('employee_maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reduces_taxable', models.BooleanField(default=False, help_text='Iuran pegawai ini mengurangi dasar perhitungan PPh21.')),
                ('employer_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Kosong = program ini tidak ditanggung perusahaan.', max_digits=9, null=True)),
                ('employer_minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('employer_maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('base_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('base_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='payroll.bpjsbasedefinition')),
                ('company', models.ForeignKey(blank=True, help_text='Kosong = aturan bawaan seluruh tenant. Diisi = aturan perusahaan itu, yang menggantikan aturan bawaan secara utuh.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bpjs_rules', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='payroll.bpjsprogram')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BPJS Rule',
                'verbose_name_plural': 'BPJS Rules',
                'db_table': 'payroll_bpjs_rule',
                'ordering': ['program__sequence', 'program__code', '-effective_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='bpjsbasedefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code', 'version'), name='uniq_active_payroll_bpjs_base_definition_version'),
        ),
        migrations.AddConstraint(
            model_name='bpjsbasecomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('definition', 'allowance_code'), name='uniq_active_payroll_bpjs_base_component'),
        ),
        migrations.AddConstraint(
            model_name='bpjsprogram',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_payroll_bpjs_program_code'),
        ),
        migrations.AddConstraint(
            model_name='bpjsenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee', 'program', 'enrolled_from'), name='uniq_active_payroll_bpjs_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='bpjsrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('program', 'company', 'effective_from'), name='uniq_active_payroll_bpjs_rule_effective', nulls_distinct=False),
        ),
    ]
