# Generated by Django 6.0.6 on 2026-09-06 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0041_backfill_calendar_scope'),
        ('payroll', '0010_alter_allowancetemplateline_basis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BpjsRiskClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Kode kelas risiko menurut konfigurasi yang berlaku.', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BPJS Risk Class',
                'verbose_name_plural': 'BPJS Risk Classes',
                'db_table': 'payroll_bpjs_risk_class',
                'ordering': ['sequence', 'code'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='bpjsrule',
            name='uniq_active_payroll_bpjs_rule_effective',
        ),
        migrations.AddField(
            model_name='bpjsbasedefinition',
            name='daily_basic_factor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Pengali upah sehari jadi dasar iuran sebulan. Wajib diisi kalau caranya Upah Harian x Pengali.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bpjsbasedefinition',
            name='daily_basic_method',
            field=models.CharField(choices=[('none', 'Tidak diatur'), ('daily_rate_x_factor', 'Upah Harian x Pengali'), ('paid_days_x_daily_rate', 'Hari Dibayar x Upah Harian')], default='none', help_text='Cara membentuk dasar iuran untuk pegawai berbasis harian. Hanya dibaca kalau kebijakan pegawainya memang harian.', max_length=30),
        ),
        migrations.AddField(
            model_name='bpjsprogram',
            name='uses_risk_class',
            field=models.BooleanField(default=False, help_text='Tarif program ini ditentukan kelas risiko kerja. Kepesertaan dan aturannya wajib menyebut kelasnya.'),
        ),
        migrations.AddField(
            model_name='bpjsriskclass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bpjsriskclass',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bpjsriskclass',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bpjsenrollment',
            name='risk_class',
            field=models.ForeignKey(blank=True, help_text='Wajib untuk program yang memakai kelas risiko, dan harus kosong untuk program yang tidak.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bpjs_enrollments', to='payroll.bpjsriskclass'),
        ),
        migrations.AddField(
            model_name='bpjsrule',
            name='risk_class',
            field=models.ForeignKey(blank=True, help_text='Wajib untuk program yang memakai kelas risiko, dan harus kosong untuk program yang tidak.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bpjs_rules', to='payroll.bpjsriskclass'),
        ),
        migrations.AddConstraint(
            model_name='bpjsrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('program', 'company', 'risk_class', 'effective_from'), name='uniq_active_payroll_bpjs_rule_effective', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='bpjsriskclass',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_active_payroll_bpjs_risk_class_code'),
        ),
    ]
