# Generated by Django 6.0.6 on 2026-09-07 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0041_backfill_calendar_scope'),
        ('payroll', '0011_bpjsriskclass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('permission_type', models.CharField(help_text='Nilai `AttendancePermissionType` di modul HR. Disimpan sebagai teks, bukan FK: jenis izin menentukan cara hitung dan tidak boleh dikarang lewat layar master.', max_length=20)),
                ('treatment', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('information_only', 'Information Only')], default='information_only', max_length=20)),
                ('unpaid_over_minutes', models.PositiveSmallIntegerField(default=0, help_text='Izin lebih lama dari sekian menit: kelebihannya dihitung tidak dibayar. Dikosongkan (0) = tidak dipakai.')),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua company yang tidak punya aturannya sendiri.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_permission_rules', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payroll_policy', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua kebijakan payroll. Diisi untuk membedakan pegawai bulanan dari harian, atau golongan yang aturannya memang berbeda.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_rules', to='payroll.payrollpolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Permission Rule',
                'verbose_name_plural': 'Payroll Permission Rules',
                'db_table': 'payroll_permission_rule',
                'ordering': ['company__code', 'permission_type'],
                'indexes': [models.Index(fields=['permission_type'], name='idx_payroll_perm_rule_type')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'payroll_policy', 'permission_type'), name='uniq_active_payroll_permission_rule')],
            },
        ),
    ]
