# Generated by Django 6.0.6 on 2026-09-23 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0042_move_fiscal_year_to_finance'),
        ('payroll', '0012_payrollpermissionrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrun',
            options={'ordering': ['-created_at'], 'permissions': [('correct_payrollrun', 'Can issue a correction payroll run')], 'verbose_name': 'Payroll Run', 'verbose_name_plural': 'Payroll Runs'},
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='corrects_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='payroll.payrollrun'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('corrects_run__isnull', False), ('status__in', ['approved', 'draft', 'finalized', 'processing', 'rejected', 'review', 'submitted'])), fields=('corrects_run',), name='uniq_active_payroll_run_successor'),
        ),
    ]
