# Generated by Django 6.0.6 on 2026-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_alter_payrollrun_options_payrollrun_corrects_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrunemployee',
            name='business_trip_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
