# Generated by Django 6.0.6 on 2026-08-06 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('profile_code', models.CharField(blank=True, default='', max_length=100)),
                ('profile_name', models.CharField(blank=True, default='', max_length=200)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveBigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imports_import_job',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportJobError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField()),
                ('employee_code', models.CharField(blank=True, default='', max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='imports.importjob')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imports_import_job_error',
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['module', 'created_at'], name='imports_imp_module_35fbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', 'created_at'], name='imports_imp_status_9aa9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='importjoberror',
            index=models.Index(fields=['job', 'row_number'], name='imports_imp_job_id_3d92c6_idx'),
        ),
        migrations.AddIndex(
            model_name='importjoberror',
            index=models.Index(fields=['job', 'field_name'], name='imports_imp_job_id_e65142_idx'),
        ),
    ]
