# Generated by Django 6.0.6 on 2026-08-06 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('uploads', '0002_uploadedfile_category_uploadedfile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='uploads.uploadedfile'),
        ),
    ]
