# Generated by Django 6.0.6 on 2026-08-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importjob_source_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(default='csv', max_length=20)),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('encoding', models.CharField(default='utf-8-sig', max_length=50)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('value_mapping', models.JSONField(blank=True, default=dict)),
                ('datetime_formats', models.JSONField(blank=True, default=list)),
                ('defaults', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imports_import_profile',
                'ordering': ['module', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['module', 'is_active'], name='idx_import_profile_module')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('module', 'code'), name='uniq_active_import_profile_code')],
            },
        ),
    ]
