# Generated by Django 6.0.6 on 2026-08-07 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_attendancestatus_code_alter_bank_code_and_more'),
        ('imports', '0003_importprofile'),
    ]

    # Migrasi ini menambah FK ke `administration.Site`, model yang
    # dihapus oleh `administration.0011_rename_site_to_location`.
    # Tanpa pernyataan urutan ini, Django bebas menjadwalkan rename lebih
    # dulu — dan replay dari nol gagal dengan
    # "Related model 'administration.site' cannot be resolved".
    #
    # Database yang sudah termigrasi tidak terpengaruh: Django cuma
    # mencatat nama migrasi, bukan isinya. Yang diperbaiki adalah
    # penyediaan tenant baru dan pembuatan database uji.
    run_before = [
        ("administration", "0011_rename_site_to_location"),
    ]

    operations = [
        migrations.AddField(
            model_name='importprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_profiles', to='administration.branch'),
        ),
        migrations.AddField(
            model_name='importprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_profiles', to='administration.company'),
        ),
        migrations.AddField(
            model_name='importprofile',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_profiles', to='administration.site'),
        ),
    ]
