# Generated by Django 6.0.6 on 2026-08-08 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_remove_holiday_uniq_core_holiday_company_site_date_and_more'),
        ('imports', '0005_rename_site_to_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_profiles', to='administration.location'),
        ),
    ]
