# Generated by Django 6.0.6 on 2026-08-15 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_rolemenupermission_visibility_rule'),
        ('administration', '0031_attendancepolicy_early_leave_leave_threshold_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='Default', max_length=100)),
                ('email_enabled', models.BooleanField(default=True, help_text='Saklar induk email untuk tenant ini. Dimatikan = seluruh email dilewati dan dicatat di log sebagai dilewati, bukan hilang tanpa jejak.')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Saklar induk notifikasi dalam aplikasi (bel).')),
                ('sender_name', models.CharField(blank=True, default='', help_text='Nama yang tampil sebagai pengirim. Dikosongkan = memakai nama aplikasi. Alamatnya sendiri tetap dari setelan server (DEFAULT_FROM_EMAIL) — mengarang alamat pengirim per tenant membuat emailnya ditolak SPF di sisi penerima.', max_length=150)),
                ('reply_to', models.EmailField(blank=True, default='', help_text='Alamat balasan, mis. hrd@perusahaan.co.id. Ini yang membuat email sistem bisa dibalas ke orang sungguhan — tanpa itu balasan mendarat di kotak no-reply yang tidak dibuka siapa pun.', max_length=254)),
                ('app_name', models.CharField(blank=True, default='', help_text='Nama aplikasi di kop dan kaki email. Dikosongkan = Meinova ERP.', max_length=100)),
                ('logo_url', models.URLField(blank=True, default='', help_text='Alamat penuh logo di kop email. Wajib absolut dan bisa diakses tanpa login — klien email tidak membawa sesi penerimanya, jadi jalur relatif dan berkas di balik autentikasi tampil sebagai gambar rusak.')),
                ('base_url', models.URLField(blank=True, default='', help_text='Alamat frontend tenant ini, mis. https://demo.meinova.id. Dipakai membangun tautan di dalam email. Dikosongkan = memakai jatuhan di settings, dan tautannya bisa mendarat di tenant lain.')),
                ('footer_text', models.TextField(blank=True, default='', help_text="Kalimat di kaki setiap email. Tempat menaruh keterangan 'email ini dikirim otomatis' dan kontak yang bisa dihubungi.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_config',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(db_index=True, help_text='Kode event, mis. hr.contract_end. Daftarnya dari registry notifikasi — event yang tidak terdaftar tidak akan pernah memicu template ini.', max_length=100)),
                ('name', models.CharField(blank=True, default='', help_text='Keterangan untuk pengelola, tidak ikut terkirim.', max_length=150)),
                ('subject', models.CharField(help_text='Judul email. Boleh memuat placeholder, mis. {{ employee_name }}.', max_length=255)),
                ('body', models.TextField(help_text='Isi email. Placeholder ditulis {{ nama_kunci }}; daftar kunci yang tersedia ada di panel sebelah dan berbeda per event.')),
                ('in_app_title', models.CharField(blank=True, default='', help_text='Judul di bel. Dikosongkan = memakai judul email. Isi kalau judul emailnya terlalu panjang untuk daftar bel.', max_length=200)),
                ('in_app_body', models.CharField(blank=True, default='', help_text='Keterangan satu baris di bawah judul bel.', max_length=255)),
                ('company', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua company. Baris yang menyebut company mengalahkan yang global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_email_template',
                'ordering': ['event', 'company__code'],
                'indexes': [models.Index(fields=['event', 'is_active'], name='notificatio_event_f1d800_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('event', 'company'), name='uniq_active_email_template_event_company')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=100)),
                ('recipient_email', models.CharField(blank=True, default='', max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('sent', 'Terkirim'), ('failed', 'Gagal'), ('skipped', 'Dilewati')], db_index=True, default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('module', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('object_type', models.CharField(blank=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('dedup_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event', 'status'], name='notificatio_event_0b0238_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_b02178_idx'), models.Index(fields=['object_type', 'object_id'], name='notificatio_object__094419_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedup_key', ''), _negated=True), fields=('dedup_key', 'recipient', 'channel'), name='uniq_notification_log_dedup')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(db_index=True, help_text='Kode event dari registry notifikasi.', max_length=100)),
                ('recipient_type', models.CharField(choices=[('subject', 'Pegawai Bersangkutan'), ('submitter', 'Pengaju'), ('pending_approver', 'Approver yang Sedang Ditagih'), ('manager', 'Atasan Langsung'), ('department_head', 'Kepala Departemen'), ('role', 'Pemegang Role'), ('user', 'Pengguna Tertentu')], default='subject', max_length=30)),
                ('manager_level', models.PositiveSmallIntegerField(default=1, help_text='Berapa tingkat naik dari pegawai bersangkutan. 1 = atasan langsung, 2 = atasannya atasan. Hanya berlaku untuk penerima bertipe Atasan Langsung.')),
                ('send_in_app', models.BooleanField(default=True, help_text='Tulis ke bel notifikasi dalam aplikasi.')),
                ('send_email', models.BooleanField(default=True, help_text='Kirim email. Tetap tunduk pada setelan masing-masing penerima — yang mematikan email di profilnya tidak dipaksa menerimanya.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, help_text='Dikosongkan = berlaku untuk semua company. Baris yang menyebut company mengalahkan yang global — dan begitu ada satu baris bercompany, baris global tidak dipakai lagi untuk company itu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='administration.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, help_text='Wajib kalau penerimanya Pemegang Role. Yang diterima masing-masing tetap disaring cakupan datanya — admin site tidak menerima pemberitahuan pegawai kantor pusat.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Wajib kalau penerimanya Pengguna Tertentu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_rule',
                'ordering': ['event', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['event', 'is_active'], name='notificatio_event_eff0ee_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('event', 'company', 'recipient_type', 'role', 'user'), name='uniq_active_notification_rule')],
            },
        ),
    ]
