# Generated by Django 6.0.6 on 2026-08-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='recipient_type',
            field=models.CharField(choices=[('subject', 'Pegawai Bersangkutan'), ('submitter', 'Pengaju'), ('pending_approver', 'Approver yang Sedang Ditagih'), ('preparer', 'Penyiap Dokumen'), ('manager', 'Atasan Langsung'), ('department_head', 'Kepala Departemen'), ('role', 'Pemegang Role'), ('user', 'Pengguna Tertentu')], default='subject', max_length=30),
        ),
    ]
